using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._VanGuard.LobbyMessage;

[GenerateTypedNameReferences]
public sealed partial class VGMessagePanel : Control
{
    public VGMessagePanel()
    {
        RobustXamlLoader.Load(this);
    }

    public void SetMessage(string? text)
    {
        if (string.IsNullOrWhiteSpace(text))
        {
            Background.Visible = false;
            return;
        }

        var message = new FormattedMessage();

        message.AddMarkupOrThrow(
            $"[font size=14][color=white]{FormattedMessage.EscapeText(text)}[/color][/font]");

        MessageLabel.SetMessage(message);

        Background.Visible = true;
    }
}