using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._VanGuard.LobbyMessage;

[GenerateTypedNameReferences]
public sealed partial class VGMessageWindow : DefaultWindow
{
    public event Action<string?>? OnSend;

    public VGMessageWindow()
    {
        RobustXamlLoader.Load(this);

        SendButton.OnPressed += _ =>
        {
            var text = MessageInput.Text;
            if (text.Length > 100)
                text = text[..100];
            OnSend?.Invoke(text);
            Close();
        };

        CancelButton.OnPressed += _ =>
        {
            OnSend?.Invoke(null);
            Close();
        };
    }
}