using System.Linq;
using Content.Client.UserInterface.Controls;
using Content.Shared._VanGuard.Language;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._VanGuard.Language.UI;

[GenerateTypedNameReferences]
public sealed partial class LanguageMenuWindow : FancyWindow
{
    private readonly LanguageSystem _language;
    private readonly IPrototypeManager _proto;

    private string? _currentLanguage;
    private Dictionary<string, LanguageKnowledge> _options = new();
    private Dictionary<string, LanguageKnowledge> _translator = new();
    private string _searchText = string.Empty;

    private readonly Dictionary<string, LanguageEntry> _entries = new();

    /// <summary>
    ///     Raised when the player selects a language.
    /// </summary>
    public event Action<string>? OnLanguageSelected;

    public LanguageMenuWindow()
    {
        RobustXamlLoader.Load(this);
        _language = IoCManager.Resolve<IEntitySystemManager>().GetEntitySystem<LanguageSystem>();
        _proto = IoCManager.Resolve<IPrototypeManager>();

        SearchBar.OnTextChanged += OnSearchTextChanged;
    }

    /// <summary>
    ///     Applies a fresh state snapshot received from the server.
    /// </summary>
    public void UpdateState(string current, Dictionary<string, LanguageKnowledge> options, Dictionary<string, LanguageKnowledge> translator)
    {
        _currentLanguage = current;
        _options = options;
        _translator = translator;

        CurrentLanguageLabel.Text = Loc.GetString("language-menu-current-language",
            ("language", _language.GetLanguageName(current)));
        LanguagesCountLabel.Text = Loc.GetString("language-menu-known-count",
            ("count", options.Count + translator.Count));

        RebuildList();
    }

    private void RebuildList()
    {
        OptionsList.RemoveAllChildren();
        _entries.Clear();

        var ids = _options.Keys.Concat(_translator.Keys).Distinct().ToList();
        ids.Sort((a, b) =>
        {
            var protoA = _proto.Index<LanguagePrototype>(a);
            var protoB = _proto.Index<LanguagePrototype>(b);

            if (protoB.Priority != protoA.Priority)
                return protoB.Priority.CompareTo(protoA.Priority);

            return string.Compare(protoA.Name, protoB.Name, StringComparison.OrdinalIgnoreCase);
        });

        foreach (var id in ids)
        {
            if (_searchText.Length > 0)
            {
                var proto = _proto.Index<LanguagePrototype>(id);
                if (!proto.Name.Contains(_searchText, StringComparison.OrdinalIgnoreCase))
                    continue;
            }

            var entry = new LanguageEntry(_proto.Index<LanguagePrototype>(id), _translator.ContainsKey(id));
            entry.UpdateSelected(id == _currentLanguage);
            entry.OnLanguageSelected += OnLanguageChosen;
            OptionsList.AddChild(entry);
            _entries[id] = entry;
        }
    }

    private void OnLanguageChosen(string languageId)
    {
        _language.RequestLanguageSwitch(languageId);
        OnLanguageSelected?.Invoke(languageId);
    }

    private void OnSearchTextChanged(LineEdit.LineEditEventArgs args)
    {
        _searchText = args.Text.Trim();
        RebuildList();
    }
}
