using Content.Client.UserInterface.Controls;
using Content.Shared._VanGuard.Language;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client._VanGuard.Language.UI;

[GenerateTypedNameReferences]
public sealed partial class LanguageEntry : PanelContainer
{
    /// <summary>
    ///     Raised with the language id when the player clicks "select".
    /// </summary>
    public event Action<string>? OnLanguageSelected;

    public string LanguageId { get; }

    public LanguageEntry(LanguagePrototype proto, bool fromTranslator)
    {
        RobustXamlLoader.Load(this);

        LanguageId = proto.ID;
        NameLabel.Text = proto.Name;
        if (proto.UiColor.HasValue)
            NameLabel.FontColorOverride = proto.UiColor.Value;

        var sprite = IoCManager.Resolve<IEntitySystemManager>().GetEntitySystem<SpriteSystem>();
        if (proto.Icon is SpriteSpecifier.Rsi rsi)
            IconTexture.Texture = sprite.Frame0(rsi);

        SelectButton.OnPressed += OnSelectPressed;

        if (fromTranslator)
            AddStyleClass("LanguageEntryTranslator");
    }

    public void UpdateSelected(bool isCurrent)
    {
        SelectButton.Disabled = isCurrent;
        SelectButton.Text = isCurrent
            ? Loc.GetString("language-choose-button-chosen")
            : Loc.GetString("language-choose-button");
    }

    private void OnSelectPressed(BaseButton.ButtonEventArgs args)
    {
        OnLanguageSelected?.Invoke(LanguageId);
    }
}
