using System.Linq;
using Content.Client.UserInterface.Controls;
using Content.Shared._VanGuard.Language;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._VanGuard.Language.UI;

[GenerateTypedNameReferences]
public sealed partial class LanguageMenuWindow : FancyWindow
{
    private readonly LanguageSystem _language;
    private readonly IPrototypeManager _proto;

    private string? _currentLanguage;
    private Dictionary<string, LanguageKnowledge> _options = new();
    private Dictionary<string, LanguageKnowledge> _translator = new();
    private string _searchText = string.Empty;

    private readonly Dictionary<string, LanguageEntry> _entries = new();

    /// <summary>
    ///     Raised when the player selects a language.
    /// </summary>
    public event Action<string>? OnLanguageSelected;

    public LanguageMenuWindow()
    {
        RobustXamlLoader.Load(this);
        _language = IoCManager.Resolve<IEntitySystemManager>().GetEntitySystem<LanguageSystem>();
        _proto = IoCManager.Resolve<IPrototypeManager>();

        SearchBar.OnTextChanged += OnSearchTextChanged;
    }

    /// <summary>
    ///     Applies a fresh state snapshot received from the server.
    /// </summary>
    public void UpdateState(string current, Dictionary<string, LanguageKnowledge> options, Dictionary<string, LanguageKnowledge> translator)
    {
        _currentLanguage = current;
        _options = options;
        _translator = translator;

        CurrentLanguageLabel.Text = Loc.GetString("language-menu-current-language",
            ("language", _language.GetLanguageName(current)));
        LanguagesCountLabel.Text = Loc.GetString("language-menu-known-count",
            ("count", options.Count + translator.Count));

        RebuildList();
    }

    private void RebuildList()
    {
        OptionsList.RemoveAllChildren();
        _entries.Clear();

        // Resolve every id exactly once and discard ids without a registered
        // LanguagePrototype.
        var prototypes = new List<LanguagePrototype>();
        foreach (var id in _options.Keys.Concat(_translator.Keys).Distinct())
        {
            if (_proto.TryIndex<LanguagePrototype>(id, out var proto))
                prototypes.Add(proto);
        }

        prototypes.Sort((a, b) =>
        {
            var priority = b.Priority.CompareTo(a.Priority);
            return priority != 0 ? priority : string.Compare(a.Name, b.Name, StringComparison.OrdinalIgnoreCase);
        });

        foreach (var proto in prototypes)
        {
            if (_searchText.Length > 0 && !proto.Name.Contains(_searchText, StringComparison.OrdinalIgnoreCase))
                continue;

            var entry = new LanguageEntry(proto, _translator.ContainsKey(proto.ID));
            entry.UpdateSelected(proto.ID == _currentLanguage);
            entry.OnLanguageSelected += OnLanguageChosen;
            OptionsList.AddChild(entry);
            _entries[proto.ID] = entry;
        }
    }

    private void OnLanguageChosen(string languageId)
    {
        _language.RequestLanguageSwitch(languageId);
        OnLanguageSelected?.Invoke(languageId);
    }

    private void OnSearchTextChanged(LineEdit.LineEditEventArgs args)
    {
        _searchText = args.Text.Trim();
        RebuildList();
    }
}
