using System;
using System.Collections.Generic;
using System.Linq;
using Content.Shared.Roles;
using JetBrains.Annotations;
using Robust.Client.AutoGenerated;
using Robust.Client.Console;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client.Administration.UI.Tabs.AdminTab
{
    [GenerateTypedNameReferences]
    [UsedImplicitly]
    public sealed partial class PlayTimeEditorWindow : DefaultWindow
    {
        [Dependency] private IPrototypeManager _prototypes = default!;
        private readonly IClientConsoleHost _consoleHost;

        private readonly List<(string Display, string Tracker)> _roles = new();
        private readonly List<(string Display, string Id)> _departments = new();

        private bool _roleMode = true;

        public PlayTimeEditorWindow()
        {
            RobustXamlLoader.Load(this);
            IoCManager.InjectDependencies(this);
            _consoleHost = IoCManager.Resolve<IClientConsoleHost>();

            Tabs.SetTabTitle(0, Loc.GetString("admin-time-panel-tab-edit"));
            Tabs.SetTabTitle(1, Loc.GetString("admin-time-panel-tab-reset"));

            BuildRoleList();
            BuildDepartmentList();
            WireEvents();
            RefreshRoleList("");
            RefreshDepartmentList("");
            SyncButtons();
            SyncClearButtons();
        }

        /// <summary>
        ///     Fills the player fields with the given username (used when opening from the admin player panel).
        /// </summary>
        public void PrefillPlayer(string username)
        {
            UserLine.Text = username;
            ClearUserLine.Text = username;
            SyncButtons();
            SyncClearButtons();
        }

        private void BuildRoleList()
        {
            _roles.Clear();
            foreach (var job in _prototypes.EnumeratePrototypes<JobPrototype>())
            {
                if (!string.IsNullOrEmpty(job.PlayTimeTracker))
                    _roles.Add((job.LocalizedName, job.PlayTimeTracker));
            }
        }

        private void BuildDepartmentList()
        {
            _departments.Clear();
            foreach (var department in _prototypes.EnumeratePrototypes<DepartmentPrototype>())
            {
                var display = Loc.TryGetString($"department-{department.ID}", out var localized)
                    ? localized
                    : department.ID;
                _departments.Add((display, department.ID));
            }
        }

        private void RefreshRoleList(string filter)
        {
            RolePick.Clear();
            var index = 0;
            foreach (var (display, tracker) in _roles
                         .Where(r => r.Display.Contains(filter, StringComparison.OrdinalIgnoreCase))
                         .OrderBy(r => r.Display))
            {
                RolePick.AddItem(display);
                RolePick.SetItemMetadata(index++, tracker);
            }

            if (RolePick.ItemCount > 0)
                RolePick.SelectId(0);
        }

        private void RefreshDepartmentList(string filter)
        {
            DepartmentPick.Clear();
            var index = 0;
            foreach (var (display, id) in _departments
                         .Where(d => d.Display.Contains(filter, StringComparison.OrdinalIgnoreCase) ||
                                     d.Id.Contains(filter, StringComparison.OrdinalIgnoreCase))
                         .OrderBy(d => d.Display))
            {
                DepartmentPick.AddItem(display);
                DepartmentPick.SetItemMetadata(index++, id);
            }

            if (DepartmentPick.ItemCount > 0)
                DepartmentPick.SelectId(0);
        }

        private void SetRoleMode(bool roleMode)
        {
            _roleMode = roleMode;
            RoleModeButton.Pressed = roleMode;
            DepartmentModeButton.Pressed = !roleMode;
            RolePick.Visible = roleMode;
            DepartmentPick.Visible = !roleMode;
            RoleSearchLine.PlaceHolder = Loc.GetString(roleMode
                ? "admin-time-panel-window-role-filtre"
                : "admin-time-panel-window-department-filtre");
            RefreshRoleList(RoleSearchLine.Text);
            RefreshDepartmentList(RoleSearchLine.Text);
        }

        private void BumpMinutes(int delta)
        {
            if (!uint.TryParse(AmountLine.Text, out var current))
                current = 0;
            AmountLine.Text = (current + delta).ToString();
            SyncButtons();
        }

        private void WireEvents()
        {
            UserLine.OnTextChanged += _ => SyncButtons();
            AmountLine.OnTextChanged += _ => SyncButtons();
            RoleSearchLine.OnTextChanged += _ =>
            {
                if (_roleMode)
                    RefreshRoleList(RoleSearchLine.Text);
                else
                    RefreshDepartmentList(RoleSearchLine.Text);
            };

            RoleModeButton.OnToggled += args =>
            {
                if (args.Pressed)
                    SetRoleMode(true);
            };
            DepartmentModeButton.OnToggled += args =>
            {
                if (args.Pressed)
                    SetRoleMode(false);
            };

            RolePick.OnItemSelected += args => RolePick.SelectId(args.Id);
            DepartmentPick.OnItemSelected += args => DepartmentPick.SelectId(args.Id);

            HourBonus.OnPressed += _ => BumpMinutes(60);
            DayBonus.OnPressed += _ => BumpMinutes(1440);
            WeekBonus.OnPressed += _ => BumpMinutes(10080);
            MonthBonus.OnPressed += _ => BumpMinutes(43200);

            GrantPlayerList.OnSelectionChanged += player =>
            {
                UserLine.Text = player?.Username ?? string.Empty;
                SyncButtons();
            };
            ClearPlayerList.OnSelectionChanged += player =>
            {
                ClearUserLine.Text = player?.Username ?? string.Empty;
                SyncClearButtons();
            };

            GrantRoleButton.OnPressed += _ => CommitRoleGrant();
            GrantOverallButton.OnPressed += _ => CommitOverallGrant();
            ClearEverythingButton.OnPressed += _ => RunClear("playtime_resetall_as");
            ClearRolesButton.OnPressed += _ => RunClear("playtime_resetroles_as");
            ClearOverallButton.OnPressed += _ => RunClear("playtime_resetoverall_as");
        }

        private void CommitRoleGrant()
        {
            if (string.IsNullOrWhiteSpace(UserLine.Text) || string.IsNullOrWhiteSpace(AmountLine.Text))
                return;

            if (_roleMode)
            {
                if (RolePick.SelectedMetadata is not string tracker || string.IsNullOrWhiteSpace(tracker))
                    return;

                _consoleHost.ExecuteCommand(
                    $"playtime_addrole_as \"{UserLine.Text}\" \"{CommandParsing.Escape(tracker)}\" {AmountLine.Text}");
            }
            else
            {
                if (DepartmentPick.SelectedMetadata is not string department || string.IsNullOrWhiteSpace(department))
                    return;

                _consoleHost.ExecuteCommand(
                    $"playtime_adddepartment_as \"{UserLine.Text}\" \"{CommandParsing.Escape(department)}\" {AmountLine.Text}");
            }
        }

        private void CommitOverallGrant()
        {
            if (string.IsNullOrWhiteSpace(UserLine.Text) || string.IsNullOrWhiteSpace(AmountLine.Text))
                return;

            _consoleHost.ExecuteCommand($"playtime_addoverall_as \"{UserLine.Text}\" {AmountLine.Text}");
        }

        private void RunClear(string command)
        {
            if (string.IsNullOrWhiteSpace(ClearUserLine.Text))
                return;

            _consoleHost.ExecuteCommand($"{command} \"{ClearUserLine.Text}\"");
        }

        private void SyncButtons()
        {
            var valid = !string.IsNullOrWhiteSpace(UserLine.Text) &&
                        uint.TryParse(AmountLine.Text, out _);
            GrantRoleButton.Disabled = !valid;
            GrantOverallButton.Disabled = !valid;
        }

        private void SyncClearButtons()
        {
            var valid = !string.IsNullOrWhiteSpace(ClearUserLine.Text);
            ClearEverythingButton.Disabled = !valid;
            ClearRolesButton.Disabled = !valid;
            ClearOverallButton.Disabled = !valid;
        }
    }
}

