using System;
using System.Globalization;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client._VanGuard.Mining.Shop;

/// <summary>
/// Compact item block for the mining shop: a square panel with the entity icon and the
/// price overlaid on it, plus the item name underneath. The visible panel is painted by
/// <see cref="CardBackground"/> while the transparent <see cref="BuyButton"/> on top
/// handles clicks, hover and the disabled state.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class MiningShopItemCard : BoxContainer
{
    private static readonly Color ColorBg = Color.FromHex("#141B24");
    private static readonly Color ColorBgHover = Color.FromHex("#1B2430");
    private static readonly Color ColorBgPressed = Color.FromHex("#212C3A");
    private static readonly Color ColorBgDisabled = Color.FromHex("#0D1115");
    private static readonly Color ColorBorder = Color.FromHex("#2E3B45");
    private static readonly Color ColorBorderHover = Color.FromHex("#C9A227");
    private static readonly Color ColorBorderPressed = Color.FromHex("#E0B52E");
    private static readonly Color ColorBorderDisabled = Color.FromHex("#1B2329");

    private readonly StyleBoxFlat _box = new()
    {
        BorderThickness = new Thickness(1),
    };

    private string _priceText = string.Empty;

    public MiningShopItemCard()
    {
        RobustXamlLoader.Load(this);

        CardBackground.PanelOverride = _box;
        RefreshVisuals();

        BuyButton.OnPressed += _ => OnPressed?.Invoke();
        BuyButton.OnDrawModeChanged += RefreshVisuals;
    }

    /// <summary>
    /// Invoked when the buy panel is pressed.
    /// </summary>
    public event Action? OnPressed;

    /// <summary>
    /// The display name used by the search filter.
    /// </summary>
    public string SearchText { get; private set; } = string.Empty;

    /// <summary>
    /// Binds this card to one shop entry.
    /// </summary>
    public void SetItem(EntProtoId protoId, string protoName, string? description)
    {
        ItemIcon.SetPrototype(protoId);
        SearchText = protoName;

        NameLabel.SetMessage(protoName, Color.FromHex("#C8D6DE"));
        BuyButton.ToolTip = description;

        var msg = new FormattedMessage();
        msg.AddText(protoName);
        msg.PushNewline();
        if (!string.IsNullOrWhiteSpace(description))
            msg.AddText(description);

        var tooltip = new Tooltip();
        tooltip.SetMessage(msg);
        tooltip.MaxWidth = 250f;
        BuyButton.TooltipDelay = 0;
        BuyButton.TooltipSupplier = _ => tooltip;

        RefreshVisuals();
    }

    /// <summary>
    /// Sets the price shown on the card.
    /// </summary>
    public void SetPrice(uint? price)
    {
        _priceText = price != null
            ? Loc.GetString("mining-shop-price", ("price", price.Value.ToString("N0", CultureInfo.InvariantCulture)))
            : string.Empty;
        ApplyPriceColor();
    }

    /// <summary>
    /// Marks the card as unaffordable (disabled).
    /// </summary>
    public void SetDisabled(bool disabled)
    {
        BuyButton.Disabled = disabled;
        RefreshVisuals();
    }

    private void ApplyPriceColor()
    {
        var color = BuyButton.Disabled ? Color.FromHex("#C45A5A") : Color.FromHex("#C9A227");
        PriceLabel.SetMessage(_priceText, color);
    }

    private void RefreshVisuals()
    {
        _box.BackgroundColor = BuyButton.DrawMode switch
        {
            BaseButton.DrawModeEnum.Pressed => ColorBgPressed,
            BaseButton.DrawModeEnum.Hover => ColorBgHover,
            BaseButton.DrawModeEnum.Disabled => ColorBgDisabled,
            _ => ColorBg,
        };

        _box.BorderColor = BuyButton.DrawMode switch
        {
            BaseButton.DrawModeEnum.Pressed => ColorBorderPressed,
            BaseButton.DrawModeEnum.Hover => ColorBorderHover,
            BaseButton.DrawModeEnum.Disabled => ColorBorderDisabled,
            _ => ColorBorder,
        };

        ApplyPriceColor();
    }
}
