using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._VanGuard.Mining.Shop;

[GenerateTypedNameReferences]
public sealed partial class MiningShopWindow : FancyWindow
{
    public MiningShopWindow()
    {
        RobustXamlLoader.Load(this);
    }
}
