using System.Linq;
using Content.Client.Corvax;
using Content.Client.Guidebook;
using Content.Client.Lobby.UI.ProfileEditorControls;
using Content.Client.UserInterface.Controls;
using Content.Corvax.Interfaces.Shared;
using Content.Shared.Body;
using Content.Shared.Humanoid;
using Content.Shared.Humanoid.Markings;
using Content.Shared.Humanoid.Prototypes;
using Content.Shared.Preferences;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.ContentPack;
using Robust.Shared.Prototypes;

namespace Content.Client._VanGuard.Lobby.UI;

/// <summary>
///     A browser window that lists every playable species and lets the player
///     inspect their appearance, strengths/weaknesses and a detailed description
///     before committing to a choice.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class SpeciesWindow : FancyWindow
{
    /// <summary>
    ///     Raised when the player confirms a species selection.
    /// </summary>
    public event Action<ProtoId<SpeciesPrototype>>? SpeciesChosen;

    private static readonly Color AdvantageColor = new(0.075f, 0.95f, 0.28f);
    private static readonly Color DrawbackColor = new(0.84f, 0.21f, 0.21f);

    private readonly HumanoidCharacterProfile _profile;
    private readonly IPrototypeManager _prototypeManager;
    private readonly IResourceManager _resourceManager;

    private ISharedSponsorsManager? _sponsorsManager;

    [Dependency] private DocumentParsingManager _parsing = default!;

    private ProtoId<SpeciesPrototype> _currentSpecies;

    public SpeciesWindow(
        HumanoidCharacterProfile profile,
        IPrototypeManager prototypeManager,
        IResourceManager resourceManager)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        IoCManager.Instance!.TryResolveType(out _sponsorsManager);

        _profile = profile;
        _prototypeManager = prototypeManager;
        _resourceManager = resourceManager;

        Title = Loc.GetString("species-window-title");

        ChooseButton.OnPressed += _ => SpeciesChosen?.Invoke(_currentSpecies);

        PopulateSpecies();
        _currentSpecies = profile.Species;
        ShowSpecies(_currentSpecies);
    }

    /// <summary>
    ///     Fills the list on the left with every round-start species the player is allowed to pick.
    /// </summary>
    private void PopulateSpecies()
    {
        var sponsored = _sponsorsManager?.GetClientPrototypes() ?? new List<string>();

        var availableSpecies = _prototypeManager.EnumeratePrototypes<SpeciesPrototype>()
            .Where(species => species.RoundStart)
            .Where(species => !species.SponsorOnly || sponsored.Contains(species.ID))
            .OrderBy(species => Loc.GetString(species.Name), StringComparer.CurrentCultureIgnoreCase)
            .ToList();

        foreach (var species in availableSpecies)
        {
            var name = Loc.GetString(species.Name);
            if (species.SponsorOnly)
                name += SponsorOnlyHelpers.GetSponsorOnlySuffix(species.ID);

            var entry = new SpeciesEntry(species.ID)
            {
                Text = name,
                ToggleMode = true,
                HorizontalExpand = true,
                Margin = new Thickness(4f),
            };

            entry.OnToggled += _ => ShowSpecies(entry.ProtoId);
            SpeciesList.AddChild(entry);
        }
    }

    /// <summary>
    ///     Displays the given species: highlights its list entry, updates the previews
    ///     and rebuilds the detail panel.
    /// </summary>
    private void ShowSpecies(ProtoId<SpeciesPrototype> speciesId)
    {
        _currentSpecies = speciesId;

        foreach (var child in SpeciesList.Children)
        {
            if (child is not SpeciesEntry entry)
                continue;

            entry.Pressed = entry.ProtoId == speciesId;
        }

        var species = _prototypeManager.Index(speciesId);

        var previewProfile = _profile.WithSpecies(speciesId);
        if (speciesId.Id != _profile.Species)
        {
            // Another species: show its canonical default look and drop foreign markings
            // (e.g. a tail on a human).
            previewProfile = ApplyDefaultSkin(previewProfile, species);
            previewProfile = ResetMarkingsForSpecies(previewProfile, speciesId);
        }
        // Otherwise this is the player's own species, so the dummy keeps their exact
        // skin tone and markings.

        NakedPreview.LoadPreview(previewProfile, null, showClothes: false);
        UniformPreview.LoadPreview(previewProfile, null, showClothes: true);

        ChooseButton.Disabled = _profile.Species == speciesId.Id;

        RebuildDetails(species);
    }

    /// <summary>
    ///     Applies the species' canonical default skin tone to the preview profile,
    ///     clamped to its coloration strategy.
    /// </summary>
    private HumanoidCharacterProfile ApplyDefaultSkin(HumanoidCharacterProfile profile, SpeciesPrototype species)
    {
        var strategy = _prototypeManager.Index(species.SkinColoration).Strategy;

        var skinColor = strategy.InputType switch
        {
            SkinColorationStrategyInput.Unary =>
                strategy.FromUnary(species.DefaultHumanSkinTone),
            _ =>
                strategy.ClosestSkinColor(species.DefaultSkinTone),
        };

        return profile.WithCharacterAppearance(profile.Appearance.WithSkinColor(skinColor));
    }

    /// <summary>
    ///     Removes markings that are not available to the given species, so switching
    ///     from e.g. Vulpkanin to Human does not leave a tail, ears or a muzzle behind.
    ///     Works on a deep copy so the player's own markings are never lost.
    /// </summary>
    private HumanoidCharacterProfile ResetMarkingsForSpecies(HumanoidCharacterProfile profile, ProtoId<SpeciesPrototype> speciesId)
    {
        var sponsored = _sponsorsManager?.GetClientPrototypes() ?? new List<string>();

        // EnsureValid mutates the marking lists it is given, so feed it a deep copy
        // instead of the original appearance (otherwise switching away and back would
        // permanently strip the character's tail, ears, etc.).
        var clonedAppearance = profile.Appearance.WithMarkings(DeepCloneMarkings(profile.Appearance.Markings));
        var appearance = HumanoidCharacterAppearance.EnsureValid(clonedAppearance, speciesId, profile.Sex, sponsored.ToArray());
        return profile.WithCharacterAppearance(appearance);
    }

    /// <summary>
    ///     Copies every nested dictionary and list so the resulting structure
    ///     shares no references with the source.
    /// </summary>
    private static Dictionary<ProtoId<OrganCategoryPrototype>, Dictionary<HumanoidVisualLayers, List<Marking>>> DeepCloneMarkings(
        Dictionary<ProtoId<OrganCategoryPrototype>, Dictionary<HumanoidVisualLayers, List<Marking>>> markings)
    {
        var result = new Dictionary<ProtoId<OrganCategoryPrototype>, Dictionary<HumanoidVisualLayers, List<Marking>>>();

        foreach (var (organ, layers) in markings)
        {
            var clonedLayers = new Dictionary<HumanoidVisualLayers, List<Marking>>();
            foreach (var (layer, layerMarkings) in layers)
                clonedLayers[layer] = new List<Marking>(layerMarkings);

            result[organ] = clonedLayers;
        }

        return result;
    }

    /// <summary>
    ///     Builds the strengths/weaknesses list and, when available, the species description.
    /// </summary>
    private void RebuildDetails(SpeciesPrototype species)
    {
        // Dispose, not just remove: embedded description entities (GuideEntityEmbed) clean up on dispose.
        Details.DisposeAllChildren();

        var traits = new List<(Color? Color, string Text)>();
        foreach (var pro in species.Pros)
            traits.Add((AdvantageColor, Loc.GetString(pro)));
        foreach (var special in species.Special)
            traits.Add((null, Loc.GetString(special)));
        foreach (var con in species.Cons)
            traits.Add((DrawbackColor, Loc.GetString(con)));

        if (traits.Count == 0)
        {
            Details.AddChild(new RichTextLabel
            {
                Text = Loc.GetString("species-window-no-strengths-weaknesses"),
                Margin = new Thickness(4f),
            });
        }
        else
        {
            Details.AddChild(new RichTextLabel
            {
                Text = Loc.GetString("species-window-strengths-weaknesses"),
                StyleClasses = { "LowDivider" },
                Margin = new Thickness(2f),
            });

            foreach (var (color, text) in traits)
            {
                var markup = color is { } entryColor ? $"[color={entryColor.ToHex()}]- {text}[/color]" : $"- {text}";
                Details.AddChild(new RichTextLabel
                {
                    Text = markup,
                    StyleClasses = { "LowDivider" },
                    Margin = new Thickness(4f, 2f),
                });
            }
        }

        if (species.Description is not { } descriptionPath)
            return;

        using var stream = _resourceManager.ContentFileReadText(descriptionPath);
        _parsing.TryAddMarkup(Details, stream.ReadToEnd());
    }

    /// <summary>
    ///     Toggleable list entry that remembers which species it represents.
    /// </summary>
    private sealed class SpeciesEntry : Button
    {
        public readonly ProtoId<SpeciesPrototype> ProtoId;

        public SpeciesEntry(ProtoId<SpeciesPrototype> protoId)
        {
            ProtoId = protoId;
        }
    }
}
