using System.Globalization;
using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._VanGuard.Economy.UI;

[GenerateTypedNameReferences]
public sealed partial class EconomyWalletWindow : FancyWindow
{
    public EconomyWalletWindow()
    {
        RobustXamlLoader.Load(this);
        ApplyStaticStyling();
    }

    private void ApplyStaticStyling()
    {
        // Field-terminal palette: the panels themselves are styled in XAML.
        SubtitleLabel.FontColorOverride = Color.FromHex("#9AA4B2");
        AccountChipLabel.FontColorOverride = Color.FromHex("#4ad9ff");
        BrandLabel.FontColorOverride = Color.FromHex("#D7B56D");
        AccountNumberLabel.FontColorOverride = Color.FromHex("#F2F4F8");

        FundsTitleLabel.FontColorOverride = Color.FromHex("#9AA4B2");
        FundsValueLabel.FontColorOverride = Color.FromHex("#67E8A5");

        WithdrawHintLabel.FontColorOverride = Color.FromHex("#9AA4B2");
        ManualWarningLabel.FontColorOverride = Color.FromHex("#E06C75");

        WithdrawButton.ModulateSelfOverride = Color.FromHex("#53C78F");
    }

    public string FormatCredits(int amount)
    {
        return Loc.GetString("economy-card-balance-value", ("balance", amount.ToString("N0", CultureInfo.InvariantCulture)));
    }

    public string MaskAccountId(string? accountId)
    {
        if (string.IsNullOrWhiteSpace(accountId))
            return Loc.GetString("economy-card-no-account");

        var trimmed = accountId.Trim();
        var suffix = trimmed.Length <= 4 ? trimmed : trimmed[^4..];
        return $"•••• •••• •••• {suffix}";
    }
}
