using Content.Shared._VanGuard.CCVars;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;

namespace Content.Client._VanGuard.Options.UI.Tabs;

[GenerateTypedNameReferences]
public sealed partial class DeltaTab : Control
{
    [Dependency] private IConfigurationManager _cfg = default!;

    public DeltaTab()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        DisableBloomCheckBox.OnToggled += OnCheckBoxToggled;
        DisableBloomCheckBox.Pressed = _cfg.GetCVar(VGCCVars.BloomEnabled);

        ApplyButton.OnPressed += OnApplyButtonPressed;
        UpdateApplyButton();
    }

    private void OnCheckBoxToggled(BaseButton.ButtonToggledEventArgs args)
    {
        UpdateApplyButton();
    }

    private void OnApplyButtonPressed(BaseButton.ButtonEventArgs args)
    {
        _cfg.SetCVar(VGCCVars.BloomEnabled, DisableBloomCheckBox.Pressed);

        _cfg.SaveToFile();
        UpdateApplyButton();
    }

    private void UpdateApplyButton()
    {
        var isBloomSame = DisableBloomCheckBox.Pressed == _cfg.GetCVar(VGCCVars.BloomEnabled);

        ApplyButton.Disabled = isBloomSame;
    }
}
