using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Administration.UI.Tabs.AdminTab
{
    [GenerateTypedNameReferences]
    public sealed partial class AdminTab : Control
    {
        // VG-Tweak Start
        private PlayTimeEditorWindow? _playtimeWindow;

        public AdminTab()
        {
            RobustXamlLoader.Load(this);

            PlaytimePanelButton.OnPressed += _ =>
            {
                _playtimeWindow ??= new PlayTimeEditorWindow();
                _playtimeWindow.OpenCentered();
                _playtimeWindow.MoveToFront();
            };
        }
        // VG-Tweak End
    }
}
