using System;
using System.Collections.Generic;
using System.Numerics;
using Content.Shared._VanGuard.NanoChat;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;
using Robust.Shared.Utility;

namespace Content.Client._VanGuard.NanoChat;

/// <summary>
///     Full-screen overlay listing the station's NanoChat directory. Chats can
///     only be started with one of the people listed here; every entry shows the
///     contact's name, job title and NanoChat number.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class NanoChatLookupView : PanelContainer
{
    private List<NanoChatRecipient>? _contacts;
    private uint _ownNumber;
    private int _maxRecipients;
    private IReadOnlyDictionary<uint, NanoChatRecipient> _recipients = new Dictionary<uint, NanoChatRecipient>();

    public NanoChatLookupView()
    {
        RobustXamlLoader.Load(this);

        PanelOverride = new StyleBoxFlat
        {
            BackgroundColor = Color.FromHex("#0A0E12"),
            BorderColor = Color.FromHex("#2E3B45"),
            BorderThickness = new Thickness(2),
        };

        // RSI states can't be addressed as plain texture paths, so load the
        // program icon through the sprite system like the research UIs do.
        var spriteSystem = IoCManager.Resolve<IEntitySystemManager>().GetEntitySystem<SpriteSystem>();
        LookupIcon.Texture = spriteSystem.Frame0(new SpriteSpecifier.Rsi(
            new ResPath("/Textures/_VanGuard/Interface/Misc/program_icons.rsi"), "nanochat"));

        CloseLookupButton.OnPressed += _ => OnClose?.Invoke();
        SearchInput.OnTextChanged += _ => RebuildContactList();
        ListNumberButton.OnPressed += _ => OnToggleListNumber?.Invoke();
    }

    /// <summary>
    ///     Fired when the user asks to start a chat with one of the contacts.
    /// </summary>
    public event Action<NanoChatRecipient>? OnStartChat;

    /// <summary>
    ///     Fired when the overlay should be closed.
    /// </summary>
    public event Action? OnClose;

    /// <summary>
    ///     Fired when the "list my number" toggle is pressed.
    /// </summary>
    public event Action? OnToggleListNumber;

    public void SetListNumber(bool listNumber)
    {
        ListNumberButton.Pressed = listNumber;
    }

    public void UpdateContactList(NanoChatUiState state)
    {
        _contacts = state.Contacts;
        _ownNumber = state.OwnNumber;
        _maxRecipients = state.MaxRecipients;
        _recipients = state.Recipients;
        ListNumberButton.Pressed = state.ListNumber;
        RebuildContactList();
    }

    private void RebuildContactList()
    {
        ContactsList.RemoveAllChildren();

        if (_contacts is not { } contacts)
        {
            ContactsList.AddChild(CreateMessageLabel(Loc.GetString("nano-chat-look-up-no-server")));
            return;
        }

        var filter = SearchInput.Text.Trim();
        foreach (var contact in contacts)
        {
            if (filter.Length > 0 && !MatchesFilter(contact, filter))
                continue;

            ContactsList.AddChild(CreateContactRow(contact));
        }

        if (ContactsList.ChildCount == 0)
            ContactsList.AddChild(CreateMessageLabel(Loc.GetString("nano-chat-look-up-no-contacts")));
    }

    private static bool MatchesFilter(NanoChatRecipient contact, string filter)
    {
        return contact.Name.Contains(filter, StringComparison.OrdinalIgnoreCase)
            || (contact.JobTitle?.Contains(filter, StringComparison.OrdinalIgnoreCase) ?? false)
            || $"#{contact.Number:D4}".Contains(filter, StringComparison.OrdinalIgnoreCase);
    }

    private static Label CreateMessageLabel(string text)
    {
        var label = new Label
        {
            Text = text,
            HorizontalAlignment = HAlignment.Center,
            HorizontalExpand = true,
            Margin = new Thickness(8, 12),
        };
        label.AddStyleClass("LabelSubText");
        return label;
    }

    private Control CreateContactRow(NanoChatRecipient contact)
    {
        var card = new PanelContainer
        {
            HorizontalExpand = true,
            Margin = new Thickness(0, 0, 0, 4),
            PanelOverride = new StyleBoxFlat
            {
                BackgroundColor = Color.FromHex("#161F27"),
                BorderColor = Color.FromHex("#2E3B45"),
                BorderThickness = new Thickness(1),
                ContentMarginLeftOverride = 8,
                ContentMarginRightOverride = 8,
                ContentMarginTopOverride = 4,
                ContentMarginBottomOverride = 4,
            },
        };

        var row = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            HorizontalExpand = true,
            VerticalAlignment = VAlignment.Center,
        };

        var info = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            HorizontalExpand = true,
            VerticalAlignment = VAlignment.Center,
        };

        info.AddChild(new Label
        {
            Text = contact.Name,
            ClipText = true,
            HorizontalExpand = true,
        });

        if (!string.IsNullOrEmpty(contact.JobTitle))
        {
            var jobLabel = new Label
            {
                Text = contact.JobTitle,
                ClipText = true,
                HorizontalExpand = true,
                FontColorOverride = Color.FromHex("#8ba0b0"),
            };
            jobLabel.AddStyleClass("LabelSubText");
            info.AddChild(jobLabel);
        }

        row.AddChild(info);

        row.AddChild(new Label
        {
            Text = $"#{contact.Number:D4}",
            FontColorOverride = Color.FromHex("#7a8a99"),
            VerticalAlignment = VAlignment.Center,
            Margin = new Thickness(8, 0, 8, 0),
        });

        var startChatButton = new Button
        {
            Text = "+",
            MinSize = new Vector2(28, 28),
            MaxSize = new Vector2(28, 28),
            VerticalAlignment = VAlignment.Center,
            ToolTip = Loc.GetString("nano-chat-new-chat"),
        };
        startChatButton.AddStyleClass("OpenBoth");

        if (contact.Number == _ownNumber
            || _recipients.ContainsKey(contact.Number)
            || _maxRecipients <= _recipients.Count)
        {
            startChatButton.Disabled = true;
        }

        startChatButton.OnPressed += _ => OnStartChat?.Invoke(contact);
        row.AddChild(startChatButton);

        card.AddChild(row);
        return card;
    }
}
