using System;
using System.Collections.Generic;
using System.Numerics;
using Content.Shared._VanGuard.NanoChat;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;
using Robust.Shared.Utility;

namespace Content.Client._VanGuard.NanoChat;

/// <summary>
///     UI for the NanoChat cartridge: conversation list, message history and the
///     station directory overlay used to start new chats.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class NanoChatUiFragment : PanelContainer
{
    private const uint MaxContentLength = NanoChatMessage.MaxContentLength;

    private readonly Dictionary<uint, NanoChatChatEntry> _entries = new();
    private NanoChatUiState? _lastState;
    private uint? _currentChat;
    private uint? _pendingChat;
    private uint _ownNumber;
    private bool _notificationsMuted;
    private bool _listNumber = true;

    public event Action<NanoChatUiMessageType, uint?, string?, string?>? OnMessageSent;

    public NanoChatUiFragment()
    {
        RobustXamlLoader.Load(this);
        HorizontalExpand = true;
        VerticalExpand = true;
        FooterHint.Text = Loc.GetString("nano-chat-footer-hint");

        // RSI states can't be addressed as plain texture paths, so load the
        // program icon through the sprite system like the research UIs do.
        var spriteSystem = IoCManager.Resolve<IEntitySystemManager>().GetEntitySystem<SpriteSystem>();
        NanoChatIcon.Texture = spriteSystem.Frame0(new SpriteSpecifier.Rsi(
            new ResPath("/Textures/_VanGuard/Interface/Misc/program_icons.rsi"), "nanochat"));

        MuteButton.OnPressed += _ =>
        {
            _notificationsMuted = !_notificationsMuted;
            UpdateMuteButton();
            OnMessageSent?.Invoke(NanoChatUiMessageType.ToggleMute, null, null, null);
        };

        LookupButton.OnPressed += _ => ToggleView();

        LookupView.OnStartChat += contact =>
        {
            if (OnMessageSent is not { } handler)
                return;

            handler(NanoChatUiMessageType.NewChat, contact.Number, contact.Name, contact.JobTitle);
            SelectChat(contact.Number);
            ToggleView();
        };

        LookupView.OnClose += ToggleView;

        LookupView.OnToggleListNumber += () =>
        {
            _listNumber = !_listNumber;
            LookupView.SetListNumber(_listNumber);
            OnMessageSent?.Invoke(NanoChatUiMessageType.ToggleListNumber, null, null, null);
        };

        DeleteChatButton.OnPressed += _ => DeleteCurrentChat();
        SendButton.OnPressed += _ => SendMessage();
        MessageInput.OnTextEntered += _ => SendMessage();
        MessageInput.OnTextChanged += OnMessageTextChanged;
    }

    /// <summary>
    ///     Opens or closes the full-screen station directory overlay.
    /// </summary>
    private void ToggleView()
    {
        LookupView.Visible = !LookupView.Visible;
        if (LookupView.Visible && _lastState != null)
            LookupView.UpdateContactList(_lastState);
    }

    private void OnMessageTextChanged(LineEdit.LineEditEventArgs args)
    {
        var length = args.Text.Length;
        var isValid = !string.IsNullOrWhiteSpace(args.Text)
            && length <= MaxContentLength
            && _currentChat != null;

        SendButton.Disabled = !isValid;

        // Show the character counter when the message is over the limit.
        CharacterCount.Visible = length > MaxContentLength;
        if (CharacterCount.Visible)
        {
            CharacterCount.Text = Loc.GetString("nano-chat-message-too-long",
                ("current", length),
                ("max", MaxContentLength));
            CharacterCount.FontColorOverride = Color.FromHex("#e05252");
        }
    }

    private void DeleteCurrentChat()
    {
        if (_currentChat is not { } chat)
            return;

        OnMessageSent?.Invoke(NanoChatUiMessageType.DeleteChat, chat, null, null);
    }

    private void SendMessage()
    {
        if (_currentChat is not { } chat)
            return;

        if (string.IsNullOrWhiteSpace(MessageInput.Text))
            return;

        // Never send an over-long message even if it slipped past the disabled
        // send button (e.g. via the Enter key); keep the draft intact.
        if (MessageInput.Text.Length > MaxContentLength)
            return;

        OnMessageSent?.Invoke(NanoChatUiMessageType.SendMessage, chat, MessageInput.Text, null);
        MessageInput.Clear();
        SendButton.Disabled = true;
        CharacterCount.Visible = false;
    }

    public void UpdateState(NanoChatUiState state)
    {
        _lastState = state;
        _ownNumber = state.OwnNumber;
        _notificationsMuted = state.NotificationsMuted;
        _listNumber = state.ListNumber;
        OwnNumberLabel.Text = Loc.GetString("nano-chat-own-number", ("number", $"{state.OwnNumber:D4}"));
        UpdateMuteButton();
        UpdateListNumber();

        // Rebuild the chat list.
        ChatList.RemoveAllChildren();
        _entries.Clear();

        foreach (var (number, recipient) in state.Recipients)
        {
            var entry = new NanoChatChatEntry(recipient, number);
            entry.OnPressed += _ => SelectChat(number);
            entry.SetUnread(recipient.HasUnread);
            _entries[number] = entry;
            ChatList.AddChild(entry);
        }

        if (state.Recipients.Count == 0)
        {
            var empty = new Label
            {
                Text = Loc.GetString("nano-chat-no-chats"),
                HorizontalAlignment = HAlignment.Center,
                HorizontalExpand = true,
                Margin = new Thickness(4, 8),
            };
            empty.AddStyleClass("LabelSubText");
            ChatList.AddChild(empty);
        }

        // Resolve a chat selection once the server confirms it. While a selection
        // is pending, keep the optimistic target so interim state updates don't
        // revert the UI to the previously open chat.
        if (_pendingChat is { } pending)
        {
            if (pending == state.CurrentChat)
            {
                _currentChat = pending;
                _pendingChat = null;
            }
        }
        else
        {
            _currentChat = state.CurrentChat;
        }

        UpdateChatView(state);
        LookupView.UpdateContactList(state);
    }

    private void SelectChat(uint number)
    {
        if (_currentChat == number)
            return;

        _pendingChat = number;
        _currentChat = number;
        OnMessageSent?.Invoke(NanoChatUiMessageType.SelectChat, number, null, null);
    }

    private void UpdateChatView(NanoChatUiState state)
    {
        var hasChat = _currentChat != null;

        NoChatLabel.Visible = !hasChat;
        MessagesScroll.Visible = hasChat;
        InputRow.Visible = hasChat;
        CurrentChatJob.Visible = hasChat;
        CurrentChatNumber.Visible = hasChat;
        DeleteChatButton.Visible = hasChat;

        // Highlight the selected entry.
        foreach (var (number, entry) in _entries)
            entry.SetSelected(number == _currentChat);

        MessageList.RemoveAllChildren();

        if (_currentChat is not { } chat)
        {
            CurrentChatName.Text = string.Empty;
            return;
        }

        if (state.Recipients.TryGetValue(chat, out var recipient))
        {
            CurrentChatName.Text = recipient.Name;
            CurrentChatJob.Text = recipient.JobTitle ?? string.Empty;
            CurrentChatJob.Visible = hasChat && !string.IsNullOrEmpty(recipient.JobTitle);
        }
        else
        {
            CurrentChatName.Text = $"#{chat:D4}";
        }

        CurrentChatNumber.Text = $"#{chat:D4}";

        if (state.Messages.TryGetValue(chat, out var messages))
        {
            foreach (var message in messages)
            {
                MessageList.AddChild(new NanoChatMessageBubble(message, message.SenderId == _ownNumber));
                MessageList.AddChild(new Control { MinSize = new Vector2(0, 4) });
            }
        }

        MessageList.InvalidateMeasure();
        MessagesScroll.InvalidateMeasure();

        // Scroll to the newest message.
        if (MessageList.Parent is ScrollContainer scroll)
            scroll.SetScrollValue(new Vector2(0, float.MaxValue));
    }

    private void UpdateMuteButton()
    {
        if (BellMutedIcon != null)
            BellMutedIcon.Visible = _notificationsMuted;
    }

    private void UpdateListNumber()
    {
        LookupView.SetListNumber(_listNumber);
    }
}

