using Content.Client.UserInterface.Controls;
using Content.Shared._VanGuard.Research.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.GameObjects;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;
using Robust.Shared.Utility;
using RobustRichTextLabel = Robust.Client.UserInterface.Controls.RichTextLabel;

namespace Content.Client._VanGuard.Research.UI;

/// <summary>
/// UI for the floor experiment scanner. Same order workflow as the handheld
/// scanner, plus a button that starts a scan of everything on the machine's tile.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class ExperimentFloorScannerMenu : FancyWindow
{
    public event Action<string>? OnSelectOrder;
    public event Action? OnAbandonOrder;
    public event Action<string>? OnSkipOrder;
    public event Action? OnSelectServer;
    public event Action? OnPerform;

    private TimeSpan _untilNextSkip = TimeSpan.Zero;
    private readonly List<Button> _skipButtons = new();

    public ExperimentFloorScannerMenu()
    {
        RobustXamlLoader.Load(this);
        MainTabs.SetTabTitle(0, Loc.GetString("experiment-scanner-tab-available"));
        MainTabs.SetTabTitle(1, Loc.GetString("experiment-scanner-tab-active"));
        AbandonButton.OnPressed += _ => OnAbandonOrder?.Invoke();
        ServerButton.OnPressed += _ => OnSelectServer?.Invoke();
        PerformButton.OnPressed += _ => OnPerform?.Invoke();
        SubtitleLabel.Text = Loc.GetString("experiment-scanner-subtitle-floor");

        var spriteSystem = IoCManager.Resolve<IEntitySystemManager>().GetEntitySystem<SpriteSystem>();
        ScannerIcon.Texture = spriteSystem.Frame0(new SpriteSpecifier.Rsi(
            new ResPath("/Textures/_VanGuard/Structures/Machines/floor_scanner.rsi"), "icon"));

        ActiveProgressBar.BackgroundStyleBoxOverride = new StyleBoxFlat
        {
            BackgroundColor = new Color(24, 20, 16)
        };
        ActiveProgressBar.ForegroundStyleBoxOverride = new StyleBoxFlat
        {
            BackgroundColor = new Color(245, 166, 35)
        };
    }

    private PanelContainer CreateOrderCard(ExperimentOrderUiData order)
    {
        var card = new PanelContainer
        {
            HorizontalExpand = true,
            Margin = new Thickness(0, 0, 0, 8),
            PanelOverride = new StyleBoxFlat
            {
                BackgroundColor = new Color(30, 24, 18),
                BorderColor = new Color(107, 74, 38),
                BorderThickness = new Thickness(1),
                ContentMarginLeftOverride = 6,
                ContentMarginRightOverride = 6,
                ContentMarginTopOverride = 6,
                ContentMarginBottomOverride = 6
            }
        };

        var content = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            HorizontalExpand = true
        };

        var name = new RobustRichTextLabel();
        name.SetMessage(FormattedMessage.FromMarkupPermissive(
            Loc.GetString("experiment-scanner-order-name", ("name", order.Name))));
        content.AddChild(name);

        var desc = new RobustRichTextLabel { HorizontalExpand = true };
        desc.SetMessage(FormattedMessage.FromMarkupPermissive(order.Description));
        content.AddChild(desc);

        content.AddChild(new RobustRichTextLabel
        {
            Text = Loc.GetString("experiment-scanner-progress",
                ("current", order.ProgressCurrent),
                ("target", order.ProgressTarget)),
            Margin = new Thickness(0, 4, 0, 0)
        });

        var reward = new RobustRichTextLabel();
        reward.SetMessage(FormattedMessage.FromMarkupPermissive(
            Loc.GetString("experiment-scanner-reward", ("points", order.RewardPoints))));
        content.AddChild(reward);

        var buttons = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            Margin = new Thickness(0, 6, 0, 0)
        };
        var selectButton = new Button
        {
            Text = Loc.GetString("experiment-scanner-take"),
            HorizontalExpand = true
        };
        selectButton.OnPressed += _ => OnSelectOrder?.Invoke(order.Id);
        buttons.AddChild(selectButton);

        var skipButton = new Button
        {
            Text = Loc.GetString("experiment-scanner-skip"),
            HorizontalExpand = true
        };
        skipButton.OnPressed += _ => OnSkipOrder?.Invoke(order.Id);
        _skipButtons.Add(skipButton);
        buttons.AddChild(skipButton);

        content.AddChild(buttons);
        card.AddChild(content);
        return card;
    }

    public void UpdateState(ExperimentFloorScannerState state)
    {
        _untilNextSkip = state.UntilNextSkip;
        if (state.HasSelectedServer)
        {
            ServerStatusLabel.SetMessage(FormattedMessage.FromMarkupPermissive(
                Loc.GetString("experiment-scanner-server-selected",
                    ("server", state.SelectedServerName ?? "-"))));
        }
        else
        {
            ServerStatusLabel.SetMessage(FormattedMessage.FromMarkupPermissive(
                Loc.GetString("experiment-scanner-server-not-selected")));
        }

        ProcessingLabel.Visible = state.IsProcessing;
        PerformButton.Disabled = state.IsProcessing || state.Active == null;
        MainTabs.SetTabTitle(0, Loc.GetString("experiment-scanner-tab-available-count", ("count", state.Available.Count)));

        AvailableContainer.DisposeAllChildren();
        _skipButtons.Clear();
        foreach (var order in state.Available)
        {
            AvailableContainer.AddChild(CreateOrderCard(order));
        }

        if (state.Active == null)
        {
            NoActiveLabel.Visible = true;
            ActiveContainer.Visible = false;
            ActiveTimeLabel.Text = string.Empty;
            MainTabs.CurrentTab = 0;
            return;
        }

        NoActiveLabel.Visible = false;
        ActiveContainer.Visible = true;
        MainTabs.CurrentTab = 1;
        ActiveNameLabel.SetMessage(FormattedMessage.FromMarkupPermissive(
            Loc.GetString("experiment-scanner-order-name", ("name", state.Active.Name))));
        ActiveDescLabel.SetMessage(FormattedMessage.FromMarkupPermissive(state.Active.Description));
        ActiveProgressLabel.Text = Loc.GetString("experiment-scanner-progress",
            ("current", state.Active.ProgressCurrent),
            ("target", state.Active.ProgressTarget));
        ActiveProgressBar.Value = state.Active.ProgressCurrent;
        ActiveProgressBar.MaxValue = Math.Max(1, state.Active.ProgressTarget);
        ActiveRewardLabel.SetMessage(FormattedMessage.FromMarkupPermissive(
            Loc.GetString("experiment-scanner-reward", ("points", state.Active.RewardPoints))));
        ActiveTimeLabel.Text = state.Active.TimeRemaining is { } wait && wait > TimeSpan.Zero
            ? Loc.GetString("experiment-scanner-wait-rescan", ("time", wait.ToString("mm\\:ss")))
            : string.Empty;
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);
        _untilNextSkip -= TimeSpan.FromSeconds(args.DeltaSeconds);
        if (_untilNextSkip > TimeSpan.Zero)
        {
            foreach (var skipButton in _skipButtons)
            {
                skipButton.Disabled = true;
                skipButton.Text = _untilNextSkip.ToString("mm\\:ss");
            }
            return;
        }

        foreach (var skipButton in _skipButtons)
        {
            skipButton.Disabled = false;
            skipButton.Text = Loc.GetString("experiment-scanner-skip");
        }
    }
}
