using System;
using System.Collections.Generic;
using System.Linq;
using System.Numerics;
using Content.Client.Research;
using Content.Client.UserInterface.Controls;
using Content.Shared.Access.Components;
using Content.Shared.Access.Systems;
using Content.Shared.Lathe;
using Content.Shared.Research.Components;
using Content.Shared.Research.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.Player;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Input;
using Robust.Shared.Log;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;
using Robust.Shared.Utility;

namespace Content.Client._VanGuard.Research.UI;

/// <summary>
/// Research console window with discipline (branch) tabs, a draggable
/// technology tree and a details panel for the selected technology.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class VGResearchConsoleMenu : FancyWindow
{
    /// <summary>Fired when the player wants to research a technology.</summary>
    public Action<string>? OnTechnologyCardPressed;

    /// <summary>Fired when the server selection button is pressed.</summary>
    public Action? OnServerButtonPressed;

    [Dependency] private IEntityManager _entity = default!;
    [Dependency] private IPrototypeManager _prototype = default!;
    [Dependency] private IPlayerManager _player = default!;
    [Dependency] private IGameTiming _gameTiming = default!;

    private readonly SharedLatheSystem _lathe;
    private readonly SpriteSystem _sprite;
    private readonly AccessReaderSystem _accessReader;

    /// <summary>The research console this window is attached to.</summary>
    public EntityUid Entity;

    /// <summary>Currently displayed research discipline (branch).</summary>
    private string _currentDiscipline = "Industrial";

    /// <summary>Currently selected technology, shown in the info panel.</summary>
    private string? _selectedTechId;

    /// <summary>Technology currently playing the quick hint fill, if any.</summary>
    private string? _quickFillTechId;

    /// <summary>Remaining seconds of the quick hint fill; survives tree rebuilds.</summary>
    private float _quickFillRemaining;

    /// <summary>Techs unlocked client-side but awaiting server confirmation.</summary>
    private readonly Dictionary<string, TimeSpan> _pendingUnlocks = new();

    /// <summary>Set when the tree must be rebuilt (e.g. after an optimistic unlock).</summary>
    private bool _treeDirty;

    /// <summary>Technologies queued for the chain-research wave, prerequisites first.</summary>
    private readonly Queue<string> _waveQueue = new();

    /// <summary>Seconds until the next queued technology of the wave is researched.</summary>
    private float _waveDelay;

    /// <summary>Delay between each technology of the chain-research wave.</summary>
    private const float WaveStaggerTime = 0.3f;

    /// <summary>Technology currently being hold-researched (green/chain fill), if any.</summary>
    private string? _holdFillTechId;

    /// <summary>Remaining seconds of the hold-research fill; survives tree rebuilds.</summary>
    private float _holdFillRemaining;

    /// <summary>Whether the tracked hold fill is a yellow chain research.</summary>
    private bool _holdFillIsChain;

    /// <summary>Whether a chain-research wave is currently running.</summary>
    private bool WaveInProgress => _waveQueue.Count > 0;

    /// <summary>Technology whose branch-research button is being held, if any.</summary>
    private string? _holdButtonTechId;

    /// <summary>Remaining seconds of the branch-research button hold; survives panel rebuilds.</summary>
    private float _holdButtonRemaining;

    /// <summary>Last received UI state; used to rebuild the window.</summary>
    private ResearchConsoleBoundInterfaceState _lastState = new(0);

    /// <summary>Disciplines currently shown as tabs, kept for rebuilds.</summary>
    private List<TechDisciplinePrototype> _disciplineProtos = new();

    private ButtonGroup _disciplineGroup = new();

    // Tree canvas pan state.
    private bool _panning;
    private Vector2 _panOffset;

    // Tree zoom state (mouse wheel). Only zoom-out is allowed - the wheel
    // brings the camera back to the default instead of zooming in further.
    private float _zoom = 1f;
    private const float MinZoom = 0.5f;
    private const float MaxZoom = 1f;

    // Tree layout: nodes are placed at <tree origin> + tech.Position * NodeSpacing * zoom.
    private const float TreeOriginX = 45f;
    private const float TreeOriginY = 30f;
    private const float NodeSpacing = 185f;

    // Fallback layout (used when a discipline has no positions in its prototypes).
    private const float FallbackColumnGap = 50f;
    private const float FallbackRowGap = 20f;

    public VGResearchConsoleMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _lathe = _entity.System<SharedLatheSystem>();
        _sprite = _entity.System<SpriteSystem>();
        _accessReader = _entity.System<AccessReaderSystem>();

        var computerSprite = new ResPath("/Textures/Structures/Machines/computers.rsi");
        ConsoleBaseIcon.Texture = _sprite.Frame0(new SpriteSpecifier.Rsi(computerSprite, "computer"));
        ConsoleScreenIcon.Texture = _sprite.Frame0(new SpriteSpecifier.Rsi(computerSprite, "rdcomp"));
        LayoutContainer.SetPosition(ConsoleBaseIcon, Vector2.Zero);
        LayoutContainer.SetPosition(ConsoleScreenIcon, Vector2.Zero);
        SubtitleLabel.Text = Loc.GetString("research-console-menu-subtitle");

        ServerButton.OnPressed += _ => OnServerButtonPressed?.Invoke();
        RecenterButton.OnPressed += _ => Recenter();
        TreeCanvas.OnKeyBindDown += OnTreeKeyDown;
        TreeCanvas.OnKeyBindUp += OnTreeKeyUp;
        TreeCanvas.ZoomRequested += OnTreeZoomRequested;
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        if (_quickFillRemaining > 0f)
            _quickFillRemaining = MathF.Max(0f, _quickFillRemaining - args.DeltaSeconds);

        // Revert optimistic unlocks the server has not confirmed in time.
        foreach (var id in _pendingUnlocks.Keys.ToList())
        {
            if (_gameTiming.CurTime - _pendingUnlocks[id] <= TimeSpan.FromSeconds(1.5))
                continue;

            _pendingUnlocks.Remove(id);
            _treeDirty = true;
        }

        // Track the hold-research fill time so it can resume after a rebuild.
        if (_holdFillTechId != null)
            _holdFillRemaining = MathF.Max(0f, _holdFillRemaining - args.DeltaSeconds);

        // Track the branch-research button hold time so it can survive panel rebuilds.
        if (_holdButtonTechId != null)
            _holdButtonRemaining = MathF.Max(0f, _holdButtonRemaining - args.DeltaSeconds);

        // Research the chain-research wave, one technology at a time.
        if (_waveQueue.Count > 0)
        {
            _waveDelay -= args.DeltaSeconds;
            if (_waveDelay <= 0f)
            {
                _waveDelay = WaveStaggerTime;
                var techId = _waveQueue.Dequeue();
                RequestUnlock(techId);
                StartQuickFill(techId);
            }
        }

        // Rebuild the tree after an optimistic unlock. This must not happen
        // while a node's own FrameUpdate is being processed (DoFrameUpdateRecursive
        // iterates the live children collection), so it is deferred to here.
        if (_treeDirty)
        {
            _treeDirty = false;
            if (_entity.TryGetComponent<TechnologyDatabaseComponent>(Entity, out var database))
            {
                RebuildTree();
                RefreshInfoPanel(database);
            }
        }
    }

    public void SetEntity(EntityUid entity)
    {
        Entity = entity;
    }

    /// <summary>
    /// Rebuilds the discipline tabs and the technology tree for the current branch.
    /// </summary>
    public void UpdatePanels(ResearchConsoleBoundInterfaceState state)
    {
        _lastState = state;

        TreeCanvas.RemoveAllChildren();
        DisciplinesContainer.RemoveAllChildren();
        _disciplineGroup = new ButtonGroup();

        if (!_entity.TryGetComponent<TechnologyDatabaseComponent>(Entity, out var database))
            return;

        // Drop optimistic unlocks that the server has confirmed.
        foreach (var id in _pendingUnlocks.Keys.ToList())
        {
            if (database.UnlockedTechnologies.Any(x => x == id))
                _pendingUnlocks.Remove(id);
        }

        // Only show disciplines this server supports (all disciplines as a fallback).
        IEnumerable<TechDisciplinePrototype> disciplines = database.SupportedDisciplines.Count > 0
            ? database.SupportedDisciplines.Select(id => _prototype.Index<TechDisciplinePrototype>(id))
            : _prototype.EnumeratePrototypes<TechDisciplinePrototype>();

        var allTech = _prototype.EnumeratePrototypes<TechnologyPrototype>().ToList();
        _disciplineProtos = disciplines
            .Where(d => allTech.Any(t => t.Discipline == d.ID && !t.Hidden))
            .OrderBy(d => Loc.GetString(d.Name))
            .ToList();

        if (_disciplineProtos.Count == 0)
            return;

        if (!_disciplineProtos.Any(d => d.ID == _currentDiscipline))
            _currentDiscipline = _disciplineProtos[0].ID;

        // Discipline (branch) tabs.
        foreach (var discipline in _disciplineProtos)
        {
            var selected = discipline.ID == _currentDiscipline;

            // Color the standard button itself with the discipline color; the
            // text stays neutral so branch names remain readable.
            var background = selected ? Darken(discipline.Color, 0.1f) : Darken(discipline.Color, 0.4f);
            var tab = new Button
            {
                Text = Loc.GetString(discipline.Name),
                ToggleMode = true,
                Pressed = selected,
                Group = _disciplineGroup,
                HorizontalExpand = true,
                VerticalExpand = true,
                Margin = new Thickness(5),
                ModulateSelfOverride = background,
            };

            // White text with a subtle shadow, readable on any branch color.
            tab.Label.FontColorOverride = Color.White;
            tab.Label.ShadowOffsetYOverride = 1;
            tab.Label.FontColorShadowOverride = new Color(0, 0, 0, 200);

            var disciplineId = discipline.ID;
            tab.OnPressed += _ => SelectDiscipline(disciplineId);
            DisciplinesContainer.AddChild(tab);
        }

        PopulateTree(database);
        RefreshInfoPanel(database);
    }
    /// <summary>
    /// Updates the points counter and the per-discipline tier display.
    /// </summary>
    public void UpdateInformationPanel(ResearchConsoleBoundInterfaceState state)
    {
        var pointsMsg = new FormattedMessage();
        pointsMsg.AddMarkupOrThrow(Loc.GetString("research-console-menu-research-points-text", ("points", state.Points)));
        ResearchAmountLabel.SetMessage(pointsMsg);

        if (!_entity.TryGetComponent<TechnologyDatabaseComponent>(Entity, out var database))
            return;

        TierDisplayContainer.RemoveAllChildren();
        foreach (var disciplineId in database.SupportedDisciplines)
        {
            var discipline = _prototype.Index<TechDisciplinePrototype>(disciplineId);

            // Research progress for this discipline: unlocked techs / all techs.
            var unlockedIds = database.UnlockedTechnologies.ToHashSet();
            unlockedIds.UnionWith(_pendingUnlocks.Keys.Select(k => new ProtoId<TechnologyPrototype>(k)));
            var allTech = _prototype.EnumeratePrototypes<TechnologyPrototype>()
                .Where(t => t.Discipline == disciplineId && !t.Hidden)
                .ToList();
            var unlockedCount = allTech.Count(t => unlockedIds.Contains(t.ID));
            var percent = allTech.Count == 0
                ? 0
                : (int)MathF.Round(unlockedCount / (float)allTech.Count * 100f);

            var percentText = percent >= 100
                ? Loc.GetString("research-console-discipline-max")
                : Loc.GetString("research-console-discipline-percent", ("percent", percent));

            var row = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                Children =
                {
                    new TextureRect
                    {
                        Texture = _sprite.Frame0(discipline.Icon),
                        TextureScale = new Vector2(2, 2),
                        VerticalAlignment = VAlignment.Center,
                        MouseFilter = MouseFilterMode.Stop,
                        ToolTip = Loc.GetString(discipline.Name),
                    },
                    new Label
                    {
                        Text = percentText,
                        VerticalAlignment = VAlignment.Center,
                        Margin = new Thickness(6, 0, 0, 0),
                    },
                    new Control { MinWidth = 12 },
                },
            };
            TierDisplayContainer.AddChild(row);
        }
    }

    /// <summary>
    /// Places the technology nodes of the current discipline onto the tree canvas.
    /// Nodes are positioned from the <c>Position</c> field of the technology
    /// prototypes (like the original); disciplines without any positions fall
    /// back to an automatic tier-column layout.
    /// </summary>
    private void PopulateTree(TechnologyDatabaseComponent database)
    {
        var discipline = _disciplineProtos.First(d => d.ID == _currentDiscipline);
        TreeCanvas.LinkColor = discipline.Color;

        var unlocked = database.UnlockedTechnologies.ToHashSet();
        unlocked.UnionWith(_pendingUnlocks.Keys.Select(k => new ProtoId<TechnologyPrototype>(k)));

        // Points that remain after the optimistic (not yet confirmed) unlocks,
        // so the branches behind a freshly researched technology light up right away.
        var optimisticPoints = GetOptimisticPoints();

        var techs = _prototype.EnumeratePrototypes<TechnologyPrototype>()
            .Where(t => t.Discipline == _currentDiscipline && !t.Hidden)
            .OrderBy(t => t.Tier)
            .ThenBy(t => Loc.GetString(t.Name))
            .ToList();

        var usePrototypePositions = techs.Any(t => t.Position != default);

        var x = TreeOriginX;
        foreach (var tierGroup in techs.GroupBy(t => t.Tier).OrderBy(g => g.Key))
        {
            var y = TreeOriginY;
            foreach (var tech in tierGroup)
            {
                var state = unlocked.Contains(tech.ID) ? TechState.Unlocked
                    : IsTechAvailable(tech, unlocked) ? TechState.Available
                    : TechState.Locked;

                var researchable = state == TechState.Available
                    && optimisticPoints >= tech.Cost
                    && !WaveInProgress;
                var chainResearchable = state == TechState.Locked
                    && !WaveInProgress
                    && TryGetResearchChain(tech.ID, unlocked, optimisticPoints) != null;

                var node = new ResearchTechnologyNode(
                    tech,
                    _sprite,
                    StateBorderColor(state),
                    tech.ID == _selectedTechId,
                    _zoom,
                    researchable,
                    chainResearchable);
                node.NodePressed += OnTreeNodePressed;
                node.NodeResearched += OnTreeNodeResearched;
                node.NodeChainResearched += OnTreeNodeChainResearched;
                node.NodeReleased += OnTreeNodeReleased;

                // Continue the quick hint fill on the rebuilt node, if one is in progress.
                if (node.Proto.ID == _quickFillTechId && _quickFillRemaining > 0f)
                {
                    node.PlayQuickFill(_quickFillRemaining);
                }
                // Continue the hold-research fill (green/chain) across rebuilds.
                else if (node.Proto.ID == _holdFillTechId && _holdFillRemaining > 0f)
                {
                    node.ResumeHoldFill(_holdFillRemaining, _holdFillIsChain);
                }

                TreeCanvas.AddChild(node);

                var position = usePrototypePositions ? NodePosition(tech) : new Vector2(x, y);

                LayoutContainer.SetPosition(node, position + _panOffset);

                if (!usePrototypePositions)
                    y += ResearchTechnologyNode.NodeHeight * _zoom + FallbackRowGap;
            }

            if (!usePrototypePositions)
                x += ResearchTechnologyNode.NodeWidth * _zoom + FallbackColumnGap;
        }
    }

    /// <summary>
    /// Selects the clicked technology and shows it in the info panel.
    /// </summary>
    private void OnTreeNodePressed(ResearchTechnologyNode node)
    {
        if (!_entity.TryGetComponent<TechnologyDatabaseComponent>(Entity, out var database))
            return;

        _selectedTechId = node.Proto.ID;
        UpdateNodeHighlights();
        ShowTechInfo(node.Proto, database);

        // Track the hold-to-research fill so it survives tree rebuilds while
        // the player keeps the mouse button held.
        if (node.Researchable || node.ChainResearchable)
        {
            _holdFillTechId = node.Proto.ID;
            _holdFillIsChain = node.ChainResearchable && !node.Researchable;
            _holdFillRemaining = ResearchTechnologyNode.FillDelay
                + (_holdFillIsChain
                    ? ResearchTechnologyNode.ChainFillDuration
                    : ResearchTechnologyNode.FillDuration);
        }
        else if (_holdFillTechId == node.Proto.ID)
        {
            _holdFillTechId = null;
        }
    }

    /// <summary>
    /// Called when the hold-to-research fill on a node completes.
    /// </summary>
    private void OnTreeNodeResearched(ResearchTechnologyNode node)
    {
        if (_holdFillTechId == node.Proto.ID)
            _holdFillTechId = null;

        RequestUnlock(node.Proto.ID);
    }

    /// <summary>
    /// Called when the yellow chain-research fill completes: queues the whole
    /// branch up to the held technology so it is researched one by one.
    /// </summary>
    private void OnTreeNodeChainResearched(ResearchTechnologyNode node)
    {
        if (_holdFillTechId == node.Proto.ID)
            _holdFillTechId = null;

        StartChainResearch(node.Proto.ID);
    }

    /// <summary>
    /// Called when the player releases the mouse button, cancelling the hold fill.
    /// </summary>
    private void OnTreeNodeReleased(ResearchTechnologyNode node)
    {
        if (_holdFillTechId == node.Proto.ID)
            _holdFillTechId = null;
    }

    /// <summary>
    /// Returns the technologies that still need to be researched to unlock the
    /// given technology: its un-researched prerequisites, recursively, then the
    /// technology itself (prerequisites first), plus their total cost.
    /// Returns null if the chain is empty (nothing to research).
    /// </summary>
    private List<string>? GetResearchChain(string techId, HashSet<ProtoId<TechnologyPrototype>> unlocked, out float totalCost)
    {
        totalCost = 0f;
        var visited = new HashSet<string>();
        var order = new List<string>();
        var ok = true;
        var cost = 0f;

        void Visit(string id)
        {
            if (!visited.Add(id))
                return;

            if (unlocked.Contains(id))
                return;

            if (!_prototype.TryIndex<TechnologyPrototype>(id, out var tech))
            {
                ok = false;
                return;
            }

            foreach (var prereq in tech.TechnologyPrerequisites)
                Visit(prereq);

            order.Add(id);
            cost += tech.Cost;
        }

        Visit(techId);

        totalCost = cost;
        return ok && order.Count > 0 ? order : null;
    }

    /// <summary>
    /// Returns the research chain to the given technology if its total cost
    /// fits into the available points, otherwise null.
    /// </summary>
    private List<string>? TryGetResearchChain(string techId, HashSet<ProtoId<TechnologyPrototype>> unlocked, float points)
    {
        var chain = GetResearchChain(techId, unlocked, out var totalCost);
        return chain != null && totalCost <= points ? chain : null;
    }

    /// <summary>
    /// Queues the research of the whole branch up to the given technology:
    /// each technology is researched one by one as a wave.
    /// </summary>
    private void StartChainResearch(string techId)
    {
        if (!_entity.TryGetComponent<TechnologyDatabaseComponent>(Entity, out var database))
            return;

        var unlocked = database.UnlockedTechnologies.ToHashSet();
        unlocked.UnionWith(_pendingUnlocks.Keys.Select(k => new ProtoId<TechnologyPrototype>(k)));

        var chain = TryGetResearchChain(techId, unlocked, GetOptimisticPoints());
        if (chain == null)
            return;

        foreach (var id in chain)
            _waveQueue.Enqueue(id);

        _waveDelay = 0f;
    }

    /// <summary>
    /// Marks the technology as unlocked on the client immediately, refreshes
    /// the tree and asks the server to unlock it. The optimistic state is
    /// reverted if the server does not confirm it in time.
    /// </summary>
    private void RequestUnlock(string techId)
    {
        _pendingUnlocks[techId] = _gameTiming.CurTime;
        _treeDirty = true;

        OnTechnologyCardPressed?.Invoke(techId);
    }

    /// <summary>
    /// Whether the technology can be researched given the (possibly optimistic)
    /// set of unlocked technologies. Mirrors the server-side check, but is
    /// evaluated against the client's optimistic state so the branches behind a
    /// freshly researched technology light up immediately instead of waiting
    /// for the server to push the updated database.
    /// </summary>
    private bool IsTechAvailable(TechnologyPrototype tech, HashSet<ProtoId<TechnologyPrototype>> unlocked)
    {
        if (tech.Hidden)
            return false;

        if (unlocked.Contains(tech.ID))
            return false;

        foreach (var prereq in tech.TechnologyPrerequisites)
        {
            if (!unlocked.Contains(prereq))
                return false;
        }

        return true;
    }

    /// <summary>
    /// Research points remaining after subtracting the cost of the optimistic
    /// (not yet confirmed) unlocks. Used so the player can immediately continue
    /// down a branch without waiting for the server round-trip.
    /// </summary>
    private float GetOptimisticPoints()
    {
        var points = _lastState.Points;
        foreach (var pending in _pendingUnlocks.Keys)
        {
            if (_prototype.TryIndex<TechnologyPrototype>(pending, out var pendingTech))
                points -= pendingTech.Cost;
        }

        return points;
    }

    /// <summary>
    /// Plays a short green fill on the tree node of the given technology as a
    /// hint that it can also be researched by holding the mouse button on it.
    /// </summary>
    private void StartQuickFill(string techId)
    {
        _quickFillTechId = techId;
        _quickFillRemaining = ResearchTechnologyNode.QuickFillDuration;

        foreach (var child in TreeCanvas.Children)
        {
            if (child is ResearchTechnologyNode node && node.Proto.ID == techId)
            {
                node.PlayQuickFill(_quickFillRemaining);
                return;
            }
        }
    }

    /// <summary>
    /// Refreshes the info panel for the currently selected technology, if any.
    /// </summary>
    private void RefreshInfoPanel(TechnologyDatabaseComponent database)
    {
        if (_selectedTechId is not { } id)
        {
            ShowPlaceholder();
            return;
        }

        if (!_prototype.TryIndex<TechnologyPrototype>(id, out var tech) || tech.Discipline != _currentDiscipline)
        {
            _selectedTechId = null;
            ShowPlaceholder();
            return;
        }

        ShowTechInfo(tech, database);
    }

    private void ShowPlaceholder()
    {
        InfoContainer.RemoveAllChildren();
        InfoContainer.AddChild(new RichTextLabel
        {
            Text = Loc.GetString("research-console-menu-select-hint"),
            StyleClasses = { "LabelSubText" },
            HorizontalAlignment = HAlignment.Center,
            Margin = new Thickness(10),
        });
    }
    /// <summary>
    /// Fills the right-hand panel with the details of the given technology.
    /// </summary>
    private void ShowTechInfo(TechnologyPrototype tech, TechnologyDatabaseComponent database)
    {
        InfoContainer.RemoveAllChildren();

        // The whole panel is built defensively: a single broken entry must never
        // leave the panel blank (it would otherwise be swallowed by the client's
        // exception tolerance and look like the click did nothing).
        try
        {
            var unlocked = database.UnlockedTechnologies.Any(x => x == tech.ID)
                || _pendingUnlocks.ContainsKey(tech.ID);

            // Whole-branch research info: the technologies still needed to unlock
            // this one (prerequisites first, then itself) and their total cost.
            var unlockedSet = database.UnlockedTechnologies.ToHashSet();
            unlockedSet.UnionWith(_pendingUnlocks.Keys.Select(k => new ProtoId<TechnologyPrototype>(k)));
            var optimisticPoints = GetOptimisticPoints();

            var available = !unlocked && IsTechAvailable(tech, unlockedSet);
            var hasAccess = _player.LocalEntity is not { } local ||
                            !_entity.TryGetComponent<AccessReaderComponent>(Entity, out var access) ||
                            _accessReader.IsAllowed(local, Entity, access);
            var canAfford = optimisticPoints >= tech.Cost;

            var chain = GetResearchChain(tech.ID, unlockedSet, out var chainTotalCost);
            var chainHasBranch = chain is { Count: > 1 };
            var chainResearchable = chainHasBranch && chainTotalCost <= optimisticPoints && !WaveInProgress;

            var discipline = _prototype.Index<TechDisciplinePrototype>(tech.Discipline);

            // Header: icon in a bordered slot + name + discipline color.
            var headerIcon = _sprite.Frame0(tech.Icon);
            const float headerMaxIconPx = 64f;
            var headerIconScale = MathF.Min(3f,
                MathF.Min(headerMaxIconPx / MathF.Max(headerIcon.Size.X, 1f),
                    headerMaxIconPx / MathF.Max(headerIcon.Size.Y, 1f)));

            var iconSlot = new PanelContainer
            {
                MinSize = new Vector2(64, 64),
                PanelOverride = new StyleBoxFlat
                {
                    BackgroundColor = new Color(18, 18, 22, 255),
                    BorderColor = new Color(58, 58, 66, 255),
                    BorderThickness = new Thickness(2),
                },
                Children =
                {
                    new TextureRect
                    {
                        Texture = headerIcon,
                        TextureScale = new Vector2(headerIconScale, headerIconScale),
                        HorizontalAlignment = HAlignment.Center,
                        VerticalAlignment = VAlignment.Center,
                    },
                },
            };

            var header = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                Children =
                {
                    iconSlot,
                    new Control { MinSize = new Vector2(12, 0) },
                    new BoxContainer
                    {
                        Orientation = BoxContainer.LayoutOrientation.Vertical,
                        HorizontalExpand = true,
                        VerticalAlignment = VAlignment.Center,
                        Children =
                        {
                            new RichTextLabel
                            {
                                Text = Loc.GetString(tech.Name),
                                StyleClasses = { "LabelHeading" },
                                HorizontalExpand = true,
                            },
                            new Label
                            {
                                Text = Loc.GetString(discipline.Name),
                                FontColorOverride = discipline.Color,
                                StyleClasses = { "LabelSubText" },
                            },
                        },
                    },
                },
            };
            InfoContainer.AddChild(header);
            InfoContainer.AddChild(new PanelContainer
            {
                StyleClasses = { "LowDivider" },
                Margin = new Thickness(0, 10),
            });

            // Details: tier, cost and prerequisites as a rich message
            // (the unlocked blueprints are listed separately below with icons).
            var description = new FormattedMessage();
            {
                description.AddMarkupOrThrow(Loc.GetString("research-console-tier-discipline-info",
                    ("tier", tech.Tier), ("color", discipline.Color),
                    ("discipline", Loc.GetString(discipline.Name))));
                description.PushNewline();

                description.AddMarkupOrThrow(Loc.GetString("research-console-cost", ("amount", tech.Cost)));
                description.PushNewline();

                if (chainTotalCost > tech.Cost)
                {
                    description.AddMarkupOrThrow(Loc.GetString("research-console-menu-chain-cost",
                        ("amount", chainTotalCost)));
                    description.PushNewline();
                }

                if (tech.TechnologyPrerequisites.Count > 0)
                {
                    description.AddMarkupOrThrow(Loc.GetString("research-console-prereqs-list-start"));
                    foreach (var prereq in tech.TechnologyPrerequisites)
                    {
                        var prereqTech = _prototype.Index(prereq);
                        description.PushNewline();
                        description.AddMarkupOrThrow(Loc.GetString("research-console-prereqs-list-entry",
                            ("text", Loc.GetString(prereqTech.Name))));
                    }
                    description.PushNewline();
                }
            }
            var descriptionLabel = new RichTextLabel
            {
                StyleClasses = { "LabelSubText" },
                HorizontalExpand = true,
            };
            descriptionLabel.SetMessage(description);
            InfoContainer.AddChild(descriptionLabel);
            InfoContainer.AddChild(new Control { MinSize = new Vector2(0, 12) });

            // Unlocked blueprints, each with its own icon (like the original).
            if (tech.RecipeUnlocks.Count > 0)
            {
                InfoContainer.AddChild(new Label
                {
                    Text = Loc.GetString("research-console-unlocks-list-start"),
                    StyleClasses = { "LabelSubHeading" },
                });
                InfoContainer.AddChild(new PanelContainer
                {
                    StyleClasses = { "LowDivider" },
                    Margin = new Thickness(0, 4, 0, 8),
                });

                foreach (var recipeId in tech.RecipeUnlocks)
                {
                    var recipe = _prototype.Index(recipeId);
                    var row = new BoxContainer
                    {
                        Orientation = BoxContainer.LayoutOrientation.Horizontal,
                        HorizontalExpand = true,
                        Margin = new Thickness(0, 2),
                    };

                    Control iconControl;
                    if (recipe.Icon != null)
                    {
                        var recipeIcon = _sprite.Frame0(recipe.Icon);
                        const float maxRecipeIconPx = 40f;
                        var recipeScale = MathF.Min(1.5f,
                            MathF.Min(maxRecipeIconPx / MathF.Max(recipeIcon.Size.X, 1f),
                                maxRecipeIconPx / MathF.Max(recipeIcon.Size.Y, 1f)));
                        iconControl = new TextureRect
                        {
                            Texture = recipeIcon,
                            TextureScale = new Vector2(recipeScale, recipeScale),
                            VerticalAlignment = VAlignment.Center,
                        };
                    }
                    else if (recipe.Result is { } result)
                    {
                        var view = new EntityPrototypeView();
                        view.SetPrototype(result);
                        iconControl = view;
                    }
                    else
                    {
                        iconControl = new Control { MinSize = new Vector2(32, 32) };
                    }

                    row.AddChild(iconControl);
                    row.AddChild(new RichTextLabel
                    {
                        Text = _lathe.GetRecipeName(recipe),
                        MaxWidth = 260,
                        HorizontalExpand = true,
                        VerticalAlignment = VAlignment.Center,
                        Margin = new Thickness(8, 0, 0, 0),
                        StyleClasses = { "LabelSubText" },
                    });
                    InfoContainer.AddChild(row);
                }

                InfoContainer.AddChild(new Control { MinSize = new Vector2(0, 8) });
            }

            // Generic (non-recipe) unlocks.
            foreach (var generic in tech.GenericUnlocks)
            {
                var genericLabel = new RichTextLabel
                {
                    Text = Loc.GetString(generic.UnlockDescription),
                    HorizontalExpand = true,
                    StyleClasses = { "LabelSubText" },
                };
                InfoContainer.AddChild(genericLabel);
            }

            // Research button.
            var researchButton = new Button
            {
                Text = Loc.GetString("research-console-menu-server-research-button"),
                Disabled = !available || !hasAccess || !canAfford || WaveInProgress,
                HorizontalExpand = true,
                MinHeight = 40,
                Margin = new Thickness(0, 12, 0, 0),
            };
            researchButton.OnPressed += _ =>
            {
                RequestUnlock(tech.ID);
                StartQuickFill(tech.ID);
            };
            InfoContainer.AddChild(researchButton);

            // Whole-branch research: requires a hold to confirm, so the player
            // cannot spend a large amount of points by accident.
            var chainResearchButton = new HoldButton
            {
                Text = Loc.GetString("research-console-menu-chain-research-button"),
                Disabled = !chainResearchable || !hasAccess,
                HorizontalExpand = true,
                MinHeight = 40,
                Margin = new Thickness(0, 4, 0, 0),
            };
            chainResearchButton.HoldStarted += () =>
            {
                _holdButtonTechId = tech.ID;
                _holdButtonRemaining = HoldButton.HoldDuration + ResearchTechnologyNode.FillDelay;
            };
            chainResearchButton.HoldCancelled += () =>
            {
                if (_holdButtonTechId == tech.ID)
                    _holdButtonTechId = null;
            };
            chainResearchButton.Confirmed += () =>
            {
                if (_holdButtonTechId == tech.ID)
                    _holdButtonTechId = null;

                StartChainResearch(tech.ID);
            };

            // Continue a hold that was interrupted by an info panel rebuild.
            if (_holdButtonTechId == tech.ID && _holdButtonRemaining > 0f)
                chainResearchButton.ResumeHold(_holdButtonRemaining);

            InfoContainer.AddChild(chainResearchButton);
        }
        catch (Exception e)
        {
            Logger.ErrorS("vg.research", "Failed to show technology info for {0}: {1}", tech.ID, e);

            InfoContainer.AddChild(new Label
            {
                Text = Loc.GetString(tech.Name),
                StyleClasses = { "LabelKeyText" },
                HorizontalAlignment = HAlignment.Center,
                Margin = new Thickness(10),
            });
            InfoContainer.AddChild(new Label
            {
                Text = Loc.GetString("research-console-menu-status-locked"),
                StyleClasses = { "LabelSubText" },
                HorizontalAlignment = HAlignment.Center,
                Margin = new Thickness(10),
            });
        }
    }
    /// <summary>
    /// Switches the displayed research discipline and rebuilds the tree.
    /// </summary>
    private void SelectDiscipline(string disciplineId)
    {
        if (disciplineId == _currentDiscipline && TreeCanvas.ChildCount > 0)
            return;

        _currentDiscipline = disciplineId;
        _selectedTechId = null;
        _panOffset = Vector2.Zero;
        _zoom = 1f;

        UpdatePanels(_lastState);
        UpdateInformationPanel(_lastState);
    }

    /// <summary>
    /// Resets the camera (pan and zoom) and rebuilds the tree at the default
    /// zoom, with every node back on its prototype-defined position.
    /// </summary>
    private void Recenter()
    {
        _panOffset = Vector2.Zero;
        _zoom = 1f;

        RebuildTree();
    }

    /// <summary>
    /// Handles clicks on the tree canvas. Node clicks are consumed by the
    /// node buttons themselves; pressing on empty canvas space pans the tree.
    /// </summary>
    private void OnTreeKeyDown(GUIBoundKeyEventArgs args)
    {
        if (args.Function != EngineKeyFunctions.Use)
            return;

        _panning = true;
    }

    private void OnTreeKeyUp(GUIBoundKeyEventArgs args)
    {
        if (args.Function == EngineKeyFunctions.Use)
            _panning = false;
    }

    /// <summary>
    /// The window is dragged normally (title bar / edges) as long as the
    /// research tree is not being panned. While panning the window must never
    /// move - the tree canvas already consumes the click.
    /// </summary>
    protected override DragMode GetDragModeFor(Vector2 relativeMousePos)
    {
        return _panning ? DragMode.None : base.GetDragModeFor(relativeMousePos);
    }

    /// <summary>
    /// Prototype-defined tree position of a technology, in canvas units.
    /// The origin anchors the top-left corner of the layout inside the canvas.
    /// The zoom factor scales the whole tree.
    /// </summary>
    private Vector2 NodePosition(TechnologyPrototype tech)
    {
        return new Vector2(
            TreeOriginX + tech.Position.X * NodeSpacing * _zoom,
            TreeOriginY + tech.Position.Y * NodeSpacing * _zoom);
    }

    /// <summary>
    /// Zooms the research tree in and out with the mouse wheel.
    /// </summary>
    private void OnTreeZoomRequested(float delta)
    {
        var newZoom = Math.Clamp(_zoom * (1f + delta * 0.1f), MinZoom, MaxZoom);
        if (Math.Abs(newZoom - _zoom) < 0.001f)
            return;

        _zoom = newZoom;
        RebuildTree();
    }

    /// <summary>
    /// Rebuilds the technology tree nodes with the current zoom level.
    /// </summary>
    private void RebuildTree()
    {
        TreeCanvas.RemoveAllChildren();
        if (_entity.TryGetComponent<TechnologyDatabaseComponent>(Entity, out var database))
            PopulateTree(database);
    }

    protected override void MouseMove(GUIMouseMoveEventArgs args)
    {
        base.MouseMove(args);

        if (!_panning)
            return;

        // Drag the whole tree along with the mouse.
        _panOffset += args.Relative;
        foreach (var child in TreeCanvas.Children)
            LayoutContainer.SetPosition(child, child.Position + args.Relative);
    }

    /// <summary>
    /// Re-applies the selection highlight to all visible nodes.
    /// </summary>
    private void UpdateNodeHighlights()
    {
        foreach (var child in TreeCanvas.Children)
        {
            if (child is ResearchTechnologyNode node)
                node.SetSelected(node.Proto.ID == _selectedTechId);
        }
    }

    private static Color StateBorderColor(TechState state) => state switch
    {
        TechState.Unlocked => Color.FromHex("#2FAE56"),
        TechState.Available => Color.FromHex("#3B7DD8"),
        _ => Color.FromHex("#4E4E55"),
    };
    /// <summary>
    /// Mixes <paramref name="amount"/> of black into the color (0-1), for a
    /// darker variant that keeps the original hue.
    /// </summary>
    private static Color Darken(Color color, float amount)
    {
        return new Color(
            color.R * (1 - amount),
            color.G * (1 - amount),
            color.B * (1 - amount),
            color.A);
    }



    private enum TechState
    {
        Locked,
        Available,
        Unlocked,
    }
}
