using System;
using System.Collections.Generic;
using System.Linq;
using System.Numerics;
using Content.Client.UserInterface.Controls;
using Content.Shared.VendingMachines;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._VanGuard.VendingMachines.UI;

/// <summary>
///     Compact 640x600 vending machine window: bank balance on top, a search bar and
///     a four-column grid of <see cref="FancyVendingMachineItemCard"/> item blocks.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class FancyVendingMachineMenu : FancyWindow
{
    [Dependency] private IPrototypeManager _prototypeManager = default!;

    private readonly Dictionary<(InventoryType Type, string ID), FancyVendingMachineItemCard> _cards = new();
    private readonly Dictionary<(InventoryType Type, string ID), string> _names = new();
    private readonly List<VendingMachineInventoryEntry> _entries = new();

    private bool _enabled;
    private bool _allForFree;
    private string _filter = string.Empty;

    /// <summary>
    ///     Invoked when the user clicks one of the item cards.
    /// </summary>
    public event Action<VendingMachineInventoryEntry>? OnItemSelected;

    public FancyVendingMachineMenu()
    {
        MinSize = SetSize = new Vector2(640, 600);
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        SearchBar.OnTextChanged += args => SetFilter(args.Text.Trim());
        EmptyLabel.Visible = false;
    }

    public void Populate(List<VendingMachineInventoryEntry> inventory, bool enabled, bool allForFree)
    {
        _enabled = enabled;
        _allForFree = allForFree;
        _entries.Clear();
        _names.Clear();

        foreach (var (_, card) in _cards)
        {
            ItemGrid.RemoveChild(card);
            card.Dispose();
        }
        _cards.Clear();

        foreach (var entry in inventory)
        {
            _entries.Add(entry);
            var card = CreateCard(entry);
            _cards[(entry.Type, entry.ID)] = card;
            ItemGrid.AddChild(card);
        }

        ApplyFilter();
    }

    public void UpdateAmounts(List<VendingMachineInventoryEntry> inventory, bool enabled)
    {
        _enabled = enabled;
        _entries.Clear();

        var seen = new HashSet<(InventoryType, string)>();
        foreach (var entry in inventory)
        {
            _entries.Add(entry);
            var key = (entry.Type, entry.ID);
            seen.Add(key);

            if (_cards.TryGetValue(key, out var card))
            {
                card.SetAmount(entry.Amount);
                card.SetDisabled(!enabled || entry.Amount == 0);
                continue;
            }

            var newCard = CreateCard(entry);
            _cards[key] = newCard;
            ItemGrid.AddChild(newCard);
        }

        foreach (var key in _cards.Keys.Where(k => !seen.Contains(k)).ToList())
        {
            var card = _cards[key];
            _cards.Remove(key);
            _names.Remove(key);
            ItemGrid.RemoveChild(card);
            card.Dispose();
        }

        ApplyFilter();
    }

    /// <summary>
    ///     Updates the balance header. A negative balance means the buyer has no
    ///     bank account.
    /// </summary>
    public void UpdateBalance(int balance)
    {
        BalanceLabel.Text = balance < 0
            ? Loc.GetString("vending-machine-ui-no-account")
            : Loc.GetString("vending-machine-ui-balance", ("balance", balance));
    }

    private void SetFilter(string filter)
    {
        _filter = filter;
        ApplyFilter();
    }

    private void ApplyFilter()
    {
        var hasMatches = false;
        foreach (var (key, card) in _cards)
        {
            _names.TryGetValue(key, out var name);
            var matches = string.IsNullOrEmpty(_filter)
                || key.ID.Contains(_filter, StringComparison.CurrentCultureIgnoreCase)
                || (name != null && name.Contains(_filter, StringComparison.CurrentCultureIgnoreCase));
            card.Visible = matches;
            hasMatches |= matches;
        }

        EmptyLabel.Text = _entries.Count == 0
            ? Loc.GetString("vending-machine-ui-out-of-stock")
            : Loc.GetString("vending-machine-ui-no-matches");
        EmptyLabel.Visible = !hasMatches;
        ItemGrid.Visible = hasMatches;
    }

    private FancyVendingMachineItemCard CreateCard(VendingMachineInventoryEntry entry)
    {
        var card = new FancyVendingMachineItemCard();
        var name = ResolveName(entry);
        _names[(entry.Type, entry.ID)] = name;
        card.SetItem(entry.ID, name, entry.Price, entry.Amount, _allForFree, _enabled);
        card.OnPressed += () => OnItemSelected?.Invoke(entry);
        return card;
    }

    private string ResolveName(VendingMachineInventoryEntry entry)
    {
        // EntityPrototype.Name is already localized (vanilla uses it directly for
        // display), so do not run it through Loc.GetString.
        if (_prototypeManager.TryIndex(entry.ID, out EntityPrototype? proto))
            return proto.Name;
        return entry.ID;
    }
}
