using System;
using Content.Shared.VendingMachines;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._VanGuard.VendingMachines.UI;

/// <summary>
///     Compact item block for <see cref="FancyVendingMachineMenu"/>: a square panel with
///     the entity icon, the price (top-left) / stock count (top-right) overlaid on it,
///     and the item name underneath. The visible panel is painted by
///     <see cref="CardBackground"/> while the transparent <see cref="BuyButton"/> on
///     top of it handles clicks, hover and the disabled state.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class FancyVendingMachineItemCard : BoxContainer
{
    private static readonly Color ColorBg = Color.FromHex("#12191E");
    private static readonly Color ColorBgHover = Color.FromHex("#18262C");
    private static readonly Color ColorBgPressed = Color.FromHex("#1E2D34");
    private static readonly Color ColorBgDisabled = Color.FromHex("#0D1215");
    private static readonly Color ColorBorder = Color.FromHex("#2A3941");
    private static readonly Color ColorBorderHover = Color.FromHex("#57B3A0");
    private static readonly Color ColorBorderPressed = Color.FromHex("#6BD9C2");
    private static readonly Color ColorBorderDisabled = Color.FromHex("#1B2329");

    private readonly StyleBoxFlat _box = new()
    {
        BorderThickness = new Thickness(1),
    };

    public FancyVendingMachineItemCard()
    {
        RobustXamlLoader.Load(this);

        CardBackground.PanelOverride = _box;
        RefreshVisuals();

        BuyButton.OnPressed += _ => OnPressed?.Invoke();
        BuyButton.OnDrawModeChanged += RefreshVisuals;
    }

    /// <summary>
    ///     Invoked when the buy panel is pressed.
    /// </summary>
    public event Action? OnPressed;

    /// <summary>
    ///     Binds this card to one inventory entry.
    /// </summary>
    public void SetItem(EntProtoId protoId, string protoName, int price, uint amount, bool allForFree, bool enabled)
    {
        ItemIcon.SetPrototype(protoId);
        BuyButton.ToolTip = protoName;

        NameLabel.SetMessage(protoName, Color.FromHex("#C8D6DE"));
        PriceLabel.SetMessage(
            allForFree || price <= 0
                ? Loc.GetString("vending-machine-ui-price-free")
                : Loc.GetString("vending-machine-ui-price", ("price", price)),
            Color.FromHex("#9FD3C7"));
        SetAmount(amount);
        SetDisabled(!enabled || amount == 0);
    }

    public void SetAmount(uint amount)
    {
        CountLabel.SetMessage(
            Loc.GetString("vending-machine-ui-count", ("count", amount)),
            Color.FromHex(amount == 0 ? "#C45A5A" : "#5C6B73"));
    }

    public void SetDisabled(bool disabled)
    {
        BuyButton.Disabled = disabled;
    }

    private void RefreshVisuals()
    {
        _box.BackgroundColor = BuyButton.DrawMode switch
        {
            BaseButton.DrawModeEnum.Pressed => ColorBgPressed,
            BaseButton.DrawModeEnum.Hover => ColorBgHover,
            BaseButton.DrawModeEnum.Disabled => ColorBgDisabled,
            _ => ColorBg,
        };

        _box.BorderColor = BuyButton.DrawMode switch
        {
            BaseButton.DrawModeEnum.Pressed => ColorBorderPressed,
            BaseButton.DrawModeEnum.Hover => ColorBorderHover,
            BaseButton.DrawModeEnum.Disabled => ColorBorderDisabled,
            _ => ColorBorder,
        };
    }
}

