// VG-Tweak Start
using System.Threading;
using System.Threading.Tasks;
using System.Linq;
// VG-Tweak End
using Content.Client.GameTicking.Managers;
using Content.Shared.PDA;
using Robust.Shared.Utility;
using Content.Shared.CartridgeLoader;
using Content.Client.Message;
using Content.Shared.AlertLevel;
using Robust.Client.UserInterface;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.XAML;
using Robust.Client.UserInterface.Controls;
using Robust.Shared.Timing;
using Robust.Shared.Prototypes; // VG-Wallpaper
using Content.Shared._VanGuard.PDA; // VG-Wallpaper

namespace Content.Client.PDA
{
    [GenerateTypedNameReferences]
    public sealed partial class PdaMenu : PdaWindow
    {
        [Dependency] private IClipboardManager _clipboard = null!;
        [Dependency] private IGameTiming _gameTiming = default!;
        [Dependency] private IEntitySystemManager _entitySystem = default!;
        [Dependency] private IPrototypeManager _protoMan = default!; // VG-Wallpaper
        private readonly AlertLevelSystem _alert = default!;
        private readonly ClientGameTicker _gameTicker;

        public const int HomeView = 0;
        public const int ProgramListView = 1;
        public const int SettingsView = 2;
        public const int ProgramContentView = 3;
        // VG-PDAScreens Start
        public const int BootViewIndex = 4;
        // VG-PDAScreens End


        private string _pdaOwner = Loc.GetString("comp-pda-ui-unknown");
        private string _owner = Loc.GetString("comp-pda-ui-unknown");
        private string _jobTitle = Loc.GetString("comp-pda-ui-unassigned");
        private string _stationName = Loc.GetString("comp-pda-ui-unknown");
        private string _alertLevel = Loc.GetString("comp-pda-ui-unknown");
        private string _instructions = Loc.GetString("comp-pda-ui-unknown");

        private bool _hasWallpaperColor; // VG-Tweak
        private bool _settingWallpaperColorFromState; // VG-Tweak
        private Color _wallpaperColor = Color.White; // VG-Tweak

        // VG-Wallpaper Start
        private List<PdaWallpaperPrototype> _wallpapers = new();
        // VG-Wallpaper End

        private int _currentView;

        // VG-PDAScreens Start
        private bool _bootScreenVisible;
        private CancellationTokenSource? _bootAnimationCts;
        private CancellationTokenSource? _fadeAnimationCts;
        // VG-PDAScreens End

        public event Action<EntityUid>? OnProgramItemPressed;
        public event Action<EntityUid>? OnUninstallButtonPressed;
        public event Action<EntityUid>? OnInstallButtonPressed;
        public event Action<Color>? OnWallpaperColorSelected; // VG-Tweak

        // VG-Wallpaper Start
        public event Action<string?, string?>? OnWallpaperRsiSelected;
        // VG-Wallpaper End

        public PdaMenu()
        {
            IoCManager.InjectDependencies(this);
            _alert = _entitySystem.GetEntitySystem<AlertLevelSystem>();
            _gameTicker = _entitySystem.GetEntitySystem<ClientGameTicker>();
            RobustXamlLoader.Load(this);

            ViewContainer.OnChildAdded += control => control.Visible = false;

            HomeButton.IconTexture = new SpriteSpecifier.Texture(new("/Textures/Interface/home.png"));
            FlashLightToggleButton.IconTexture = new SpriteSpecifier.Texture(new("/Textures/Interface/light.png"));
            EjectPenButton.IconTexture = new SpriteSpecifier.Texture(new("/Textures/Interface/pencil.png"));
            EjectIdButton.IconTexture = new SpriteSpecifier.Texture(new("/Textures/Interface/eject.png"));
            EjectPaiButton.IconTexture = new SpriteSpecifier.Texture(new("/Textures/Interface/pai.png"));
            // VG-Tweak Start
            PowerOffButton.IconTexture = new SpriteSpecifier.Texture(new("/Textures/_VanGuard/Interface/power.png"));
            // VG-Tweak End
            ProgramCloseButton.IconTexture = new SpriteSpecifier.Texture(new("/Textures/Interface/Nano/cross.svg.png"));


            HomeButton.OnPressed += _ => ToHomeScreen();

            ProgramListButton.OnPressed += _ =>
            {
                HomeButton.IsCurrent = false;
                ProgramListButton.IsCurrent = true;
                SettingsButton.IsCurrent = false;
                ProgramTitle.IsCurrent = false;

                ChangeView(ProgramListView);
            };


            SettingsButton.OnPressed += _ =>
            {
                HomeButton.IsCurrent = false;
                ProgramListButton.IsCurrent = false;
                SettingsButton.IsCurrent = true;
                ProgramTitle.IsCurrent = false;

                ChangeView(SettingsView);
            };

            ProgramTitle.OnPressed += _ =>
            {
                HomeButton.IsCurrent = false;
                ProgramListButton.IsCurrent = false;
                SettingsButton.IsCurrent = false;
                ProgramTitle.IsCurrent = true;

                ChangeView(ProgramContentView);
            };

            ProgramCloseButton.OnPressed += _ =>
            {
                HideProgramHeader();
                ToHomeScreen();
            };

            PdaOwnerButton.OnPressed += _ =>
            {
                _clipboard.SetText(_pdaOwner);
            };

            IdInfoButton.OnPressed += _ =>
            {
                _clipboard.SetText(_owner + ", " + _jobTitle);
            };

            StationNameButton.OnPressed += _ =>
            {
                _clipboard.SetText(_stationName);
            };

            StationAlertLevelButton.OnPressed += _ =>
            {
                _clipboard.SetText(_alertLevel);
            };

            StationTimeButton.OnPressed += _ =>
            {
                var stationTime = _gameTiming.CurTime.Subtract(_gameTicker.RoundStartTimeSpan);
                _clipboard.SetText((stationTime.ToString("hh\\:mm\\:ss")));
            };

            StationAlertLevelInstructionsButton.OnPressed += _ =>
            {
                _clipboard.SetText(_instructions);
            };

            // VG-Tweak Start
            WallpaperColorSelector.OnColorChanged += color =>
            {
                if (_settingWallpaperColorFromState)
                    return;

                _hasWallpaperColor = true;
                _wallpaperColor = color.WithAlpha(1f);
                WallpaperColor = _wallpaperColor;

                if (!WallpaperColorSelector.IsGrabbed)
                    OnWallpaperColorSelected?.Invoke(_wallpaperColor);
            };

            WallpaperColorSelector.OnColorReleased += color =>
            {
                _hasWallpaperColor = true;
                _wallpaperColor = color.WithAlpha(1f);
                WallpaperColor = _wallpaperColor;
                OnWallpaperColorSelected?.Invoke(_wallpaperColor);
            };
            // VG-Tweak End

            // VG-Wallpaper Start
            InitializeWallpaperSelector();
            // VG-Wallpaper End

            // VG-PDAScreens Start
            BootView.Visible = false;
            BootView.Modulate = Color.White;
            // VG-PDAScreens End

            HideAllViews();
            ToHomeScreen();
        }

        // VG-Wallpaper Start
        private void InitializeWallpaperSelector()
        {
            // Сортируем: сначала none, затем остальные по ID
            _wallpapers = _protoMan.EnumeratePrototypes<PdaWallpaperPrototype>()
                .OrderBy(w => w.ID == "PdaWallpaperNone" ? 0 : 1) // none всегда первый
                .ThenBy(w => w.ID)
                .ToList();

            foreach (var wallpaper in _wallpapers)
            {
                WallpaperDropdown.AddItem(Loc.GetString(wallpaper.Name));
            }

            WallpaperDropdown.OnItemSelected += OnWallpaperDropdownSelected;
        }

        private void OnWallpaperDropdownSelected(OptionButton.ItemSelectedEventArgs args)
        {
            WallpaperDropdown.SelectId(args.Id);
            var wallpaper = _wallpapers[args.Id];
            
            // Если выбран none - отправляем null, чтобы отключить обои
            if (wallpaper.ID == "PdaWallpaperNone")
            {
                OnWallpaperRsiSelected?.Invoke(null, null);
            }
            else
            {
                OnWallpaperRsiSelected?.Invoke(wallpaper.RsiPath, wallpaper.State);
            }
        }

        private void UpdateDropdownSelection(string? rsiPath, string? state)
        {
            if (rsiPath == null || state == null)
            {
                WallpaperDropdown.SelectId(0);
                return;
            }

            for (int i = 0; i < _wallpapers.Count; i++)
            {
                var wallpaper = _wallpapers[i];
                if (wallpaper.RsiPath == rsiPath && wallpaper.State == state)
                {
                    WallpaperDropdown.SelectId(i);
                    return;
                }
            }
            WallpaperDropdown.SelectId(0);
        }
        // VG-Wallpaper End

        // VG-PDAScreens Start
        public void ShowBootScreen(bool show)
        {
            if (show == _bootScreenVisible)
                return;

            _bootScreenVisible = show;
            if (show)
            {
                _bootAnimationCts?.Cancel();
                _bootAnimationCts = new CancellationTokenSource();
                _ = AnimateBootIcon(_bootAnimationCts.Token);

                BootWelcomeLabel.Text = Loc.GetString("pda-boot-welcome");
                BootView.Modulate = Color.White;
                ChangeView(BootViewIndex);
                NavigationBar.Visible = false;
                ContentFooter.Visible = false;
            }
            else
            {
                _bootAnimationCts?.Cancel();
                _bootAnimationCts = null;
                _ = FadeOutBootAndShowMain();
            }
        }

        private async Task FadeOutBootAndShowMain()
        {
            _fadeAnimationCts?.Cancel();
            _fadeAnimationCts = new CancellationTokenSource();
            var token = _fadeAnimationCts.Token;

            float opacity = 1f;
            float step = 0.05f;
            while (opacity > 0 && !token.IsCancellationRequested)
            {
                opacity -= step;
                if (opacity < 0) opacity = 0;
                BootView.Modulate = new Color(1f, 1f, 1f, opacity);
                await Task.Delay(16, token);
            }

            BootView.Visible = false;
            BootView.Modulate = Color.White;

            var mainView = ViewContainer.GetChild(HomeView);
            mainView.Visible = true;
            mainView.Modulate = new Color(1f, 1f, 1f, 0f);

            opacity = 0f;
            while (opacity < 1f && !token.IsCancellationRequested)
            {
                opacity += step;
                if (opacity > 1f) opacity = 1f;
                mainView.Modulate = new Color(1f, 1f, 1f, opacity);
                await Task.Delay(16, token);
            }

            for (int i = 0; i < ViewContainer.ChildCount; i++)
            {
                ViewContainer.GetChild(i).Modulate = Color.White;
            }

            ToHomeScreen();

            NavigationBar.Visible = true;
            ContentFooter.Visible = true;
            _bootScreenVisible = false;

            _fadeAnimationCts = null;
        }

        private async Task AnimateBootIcon(CancellationToken token)
        {
            float opacity = 1f;
            float step = 0.05f;
            bool increasing = false;

            while (!token.IsCancellationRequested)
            {
                if (increasing)
                {
                    opacity += step;
                    if (opacity >= 1f)
                    {
                        opacity = 1f;
                        increasing = false;
                    }
                }
                else
                {
                    opacity -= step;
                    if (opacity <= 0.3f)
                    {
                        opacity = 0.3f;
                        increasing = true;
                    }
                }

                BootIcon.Modulate = new Color(1f, 1f, 1f, opacity);
                await Task.Delay(50, token);
            }

            BootIcon.Modulate = Color.White;
        }
        // VG-PDAScreens End

        public void UpdateState(PdaUpdateState state)
        {
            FlashLightToggleButton.IsActive = state.FlashlightEnabled;
            // VG-PDAScreens Start
            PowerOffButton.IsActive = state.Powered;
            // VG-PDAScreens End

            // VG-Wallpaper Start
            if (state.WallpaperRsi != null && state.WallpaperState != null)
            {
                Wallpaper = (state.WallpaperRsi, state.WallpaperState);
                UpdateDropdownSelection(state.WallpaperRsi, state.WallpaperState);
            }
            else
            {
                Wallpaper = null;
                WallpaperDropdown.SelectId(0);
                var effectiveWallpaperColor = state.HasWallpaperColor
                    ? state.WallpaperColor
                    : DefaultWallpaperColor ?? state.WallpaperColor;

                WallpaperColor = state.HasWallpaperColor ? state.WallpaperColor : null;
                if (!WallpaperColorSelector.IsGrabbed &&
                    (state.HasWallpaperColor != _hasWallpaperColor ||
                    !ColorsClose(effectiveWallpaperColor, _wallpaperColor)))
                {
                    _settingWallpaperColorFromState = true;
                    WallpaperColorSelector.Color = effectiveWallpaperColor;
                    _settingWallpaperColorFromState = false;
                }

                _hasWallpaperColor = state.HasWallpaperColor;
                _wallpaperColor = effectiveWallpaperColor;
            }
            // VG-Wallpaper End

            if (state.PdaOwnerInfo.ActualOwnerName != null)
            {
                _pdaOwner = state.PdaOwnerInfo.ActualOwnerName;
                PdaOwnerLabel.SetMarkup(Loc.GetString("comp-pda-ui-owner",
                    ("actualOwnerName", _pdaOwner)));
                PdaOwnerLabel.Visible = true;
            }
            else
            {
                PdaOwnerLabel.Visible = false;
            }


            if (state.PdaOwnerInfo.IdOwner != null || state.PdaOwnerInfo.JobTitle != null)
            {
                _owner = state.PdaOwnerInfo.IdOwner ?? Loc.GetString("comp-pda-ui-unknown");
                _jobTitle = state.PdaOwnerInfo.JobTitle ?? Loc.GetString("comp-pda-ui-unassigned");
                IdInfoLabel.SetMarkup(Loc.GetString("comp-pda-ui",
                    ("owner", _owner),
                    ("jobTitle", _jobTitle)));
            }
            else
            {
                IdInfoLabel.SetMarkup(Loc.GetString("comp-pda-ui-blank"));
            }

            _stationName = state.StationName ?? Loc.GetString("comp-pda-ui-unknown");
            StationNameLabel.SetMarkup(Loc.GetString("comp-pda-ui-station",
                ("station", _stationName)));


            var stationTime = _gameTiming.CurTime.Subtract(_gameTicker.RoundStartTimeSpan);

            StationTimeLabel.SetMarkup(Loc.GetString("comp-pda-ui-station-time",
                ("time", stationTime.ToString("hh\\:mm\\:ss"))));

            var alertColor = state.PdaOwnerInfo.StationAlertColor;
            (_alertLevel, _, _instructions) = _alert.AlertLevelData(state.PdaOwnerInfo.StationAlertLevel);

            StationAlertLevelLabel.SetMarkup(Loc.GetString(
                "comp-pda-ui-station-alert-level",
                ("color", alertColor),
                ("level", _alertLevel)
            ));
            StationAlertLevelInstructions.SetMarkup(Loc.GetString(
                "comp-pda-ui-station-alert-level-instructions",
                ("instructions", _instructions))
            );

            AddressLabel.Text = state.Address?.ToUpper() ?? " - ";

            EjectIdButton.IsActive = state.PdaOwnerInfo.IdOwner != null || state.PdaOwnerInfo.JobTitle != null;
            EjectPenButton.IsActive = state.HasPen;
            EjectPaiButton.IsActive = state.HasPai;
            ActivateMusicButton.Visible = state.CanPlayMusic;
            ShowUplinkButton.Visible = state.HasUplink;
            LockUplinkButton.Visible = state.HasUplink;
        }

        public void UpdateAvailablePrograms(List<(EntityUid, CartridgeComponent)> programs)
        {
            if (programs.Count == 0)
            {
                ProgramList.RemoveAllChildren();

                ProgramList.AddChild(new Label()
                {
                    Text = Loc.GetString("comp-pda-io-no-programs-available"),
                    HorizontalAlignment = HAlignment.Center,
                    VerticalAlignment = VAlignment.Center,
                    VerticalExpand = true
                });

                return;
            }

            if (ProgramList.ChildCount >= 1 && ProgramList.Children[0] is Label label)
            {
                label.Orphan();
            }

            while (ProgramList.ChildCount > programs.Count)
            {
                ProgramList.Children[ProgramList.ChildCount - 1].Orphan();
            }

            for (var i = 0; i < programs.Count; i++)
            {
                var cartridge = programs[i];

                if (i < ProgramList.ChildCount)
                {
                    var currentItem = ProgramList.Children[i];
                    if (currentItem is PdaProgramItem programItem)
                    {
                        programItem.SetCartridge(cartridge);
                        continue;
                    }

                    DebugTools.Assert(i == ProgramList.ChildCount-1);
                    currentItem.Orphan();
                }

                var item = new PdaProgramItem(cartridge);
                item.OnProgramItemPressed += uid => OnProgramItemPressed?.Invoke(uid);
                item.OnUninstallButtonPressed += uid => OnUninstallButtonPressed?.Invoke(uid);
                item.OnInstallButtonPressed += uid => OnInstallButtonPressed?.Invoke(uid);
                ProgramList.AddChild(item);
            }

            //Add a filler item to the last row when it only contains one item
            if (programs.Count % 2 == 0)
                 ProgramList.AddChild(new Control() { HorizontalExpand = true });
        }

        /// <summary>
        /// Changes the current view to the home screen (view 0) and sets the tabs `IsCurrent` flag accordingly
        /// </summary>
        public void ToHomeScreen()
        {
            HomeButton.IsCurrent = true;
            ProgramListButton.IsCurrent = false;
            SettingsButton.IsCurrent = false;
            ProgramTitle.IsCurrent = false;

            ChangeView(HomeView);
        }

        /// <summary>
        /// Hides the program title and close button.
        /// </summary>
        public void HideProgramHeader()
        {
            ProgramTitle.IsCurrent = false;
            ProgramTitle.Visible = false;
            ProgramCloseButton.Visible = false;
            ProgramListButton.Visible = true;
            SettingsButton.Visible = true;
        }

        /// <summary>
        /// Changes the current view to the program content view (view 3), sets the program title and sets the tabs `IsCurrent` flag accordingly
        /// </summary>
        public void ToProgramView(string title)
        {
            HomeButton.IsCurrent = false;
            ProgramListButton.IsCurrent = false;
            SettingsButton.IsCurrent = false;
            ProgramTitle.IsCurrent = false;
            ProgramTitle.IsCurrent = true;
            ProgramTitle.Visible = true;
            ProgramCloseButton.Visible = true;
            ProgramListButton.Visible = false;
            SettingsButton.Visible = false;

            ProgramTitle.LabelText = title;
            ChangeView(ProgramContentView);
        }


        /// <summary>
        /// Changes the current view to the given view number
        /// </summary>
        public void ChangeView(int view)
        {
            if (ViewContainer.ChildCount <= view)
                return;

            if (_currentView >= 0 && _currentView < ViewContainer.ChildCount)
                ViewContainer.GetChild(_currentView).Visible = false;

            ViewContainer.GetChild(view).Visible = true;
            _currentView = view;
        }

        private void HideAllViews()
        {
            var views = ViewContainer.Children;
            foreach (var view in views)
            {
                view.Visible = false;
            }
        }

        private static bool ColorsClose(Color a, Color b) // VG-Tweak
        {
            const float epsilon = 0.001f;
            return System.Math.Abs(a.R - b.R) < epsilon
                && System.Math.Abs(a.G - b.G) < epsilon
                && System.Math.Abs(a.B - b.B) < epsilon
                && System.Math.Abs(a.A - b.A) < epsilon;
        }

        protected override void Draw(DrawingHandleScreen handle)
        {
            base.Draw(handle);

            var stationTime = _gameTiming.CurTime.Subtract(_gameTicker.RoundStartTimeSpan);

            StationTimeLabel.SetMarkup(Loc.GetString("comp-pda-ui-station-time",
                ("time", stationTime.ToString("hh\\:mm\\:ss"))));
        }
    }
}