using System.Numerics;
using Robust.Client.AutoGenerated;
// VG-Tweak Start
using Robust.Client.Graphics; 
using Robust.Client.ResourceManagement;
using Robust.Shared.Utility;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
// VG-Tweak End
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.IoC; // VG-Wallpaper
using Robust.Shared.Graphics.RSI; // VG-Wallpaper

namespace Content.Client.PDA;

[Virtual]
[GenerateTypedNameReferences]
public partial class PdaWindow : BaseWindow
{
    private Color? _defaultWallpaperColor;
    private Color? _wallpaperColor;
    private readonly IResourceCache _resourceCache; // VG-Wallpaper

    // VG-Wallpaper Start
    private string? _wallpaperRsi;
    private string? _wallpaperState;
    // VG-Wallpaper End

    public string? BorderColor
    {
        get => Background.ActualModulateSelf.ToHex();
        set => Background.ModulateSelfOverride = Color.FromHex(value, Color.White);
    }

    public string? AccentHColor
    {
        get => AccentH.ActualModulateSelf.ToHex();
        set
        {
            AccentH.ModulateSelfOverride = Color.FromHex(value, Color.White);
            AccentH.Visible = value != null;
        }
    }

    public string? AccentVColor
    {
        get => AccentV.ActualModulateSelf.ToHex();
        set
        {
            AccentV.ModulateSelfOverride = Color.FromHex(value, Color.White);
            AccentV.Visible = value != null;
        }
    }

    public Color? WallpaperColor
    {
        get => _wallpaperColor;
        set
        {
            _wallpaperColor = value;
            UpdateWallpaper();
        }
    }

    public Color? DefaultWallpaperColor
    {
        get => _defaultWallpaperColor;
        set
        {
            _defaultWallpaperColor = value;
            UpdateWallpaper();
        }
    }

    // VG-Wallpaper Start
    public (string Rsi, string State)? Wallpaper
    {
        get => _wallpaperRsi != null && _wallpaperState != null 
            ? (_wallpaperRsi, _wallpaperState) 
            : null;
        set
        {
            if (value.HasValue && !string.IsNullOrEmpty(value.Value.Rsi) && !string.IsNullOrEmpty(value.Value.State))
            {
                _wallpaperRsi = value.Value.Rsi;
                _wallpaperState = value.Value.State;
            }
            else
            {
                _wallpaperRsi = null;
                _wallpaperState = null;
            }
            UpdateWallpaper();
        }
    }
    // VG-Wallpaper End

    public PdaWindow()
    {
        _resourceCache = IoCManager.Resolve<IResourceCache>();
        RobustXamlLoader.Load(this);

        CloseButton.OnPressed += _ => Close();
        XamlChildren = ContentsContainer.Children;

        AccentH.Visible = false;
        AccentV.Visible = false;
    }

    protected override DragMode GetDragModeFor(Vector2 relativeMousePos)
    {
        return DragMode.Move;
    }

    private void UpdateWallpaper()
    {
        // VG-Wallpaper Start
        if (_wallpaperRsi != null && _wallpaperState != null)
        {
            SetWallpaperFromRsi(_wallpaperRsi, _wallpaperState);
            return;
        }
        // VG-Wallpaper End

        ContentBackground.ModulateSelfOverride = _wallpaperColor ?? _defaultWallpaperColor;
        ContentBackground.PanelOverride = null;
    }

    // VG-Wallpaper Start
    private void SetWallpaperFromRsi(string rsiPath, string state)
    {
        try
        {
            var rsiResource = _resourceCache.GetResource<RSIResource>(new ResPath(rsiPath));
            if (rsiResource != null && rsiResource.RSI.TryGetState(state, out var rsiState))
            {
                // Используем RsiDirection.South и индекс кадра 0
                var texture = rsiState.GetFrame(RsiDirection.South, 0);
                var styleBox = new StyleBoxTexture();
                styleBox.Texture = texture;
                styleBox.SetPatchMargin(StyleBox.Margin.All, 0);

                ContentBackground.ModulateSelfOverride = Color.White;
                ContentBackground.PanelOverride = styleBox;
                return;
            }
        }
        catch { }

        // fallback
        ContentBackground.ModulateSelfOverride = _wallpaperColor ?? _defaultWallpaperColor;
        ContentBackground.PanelOverride = null;
    }
    // VG-Wallpaper End
}