using System.Linq;
using System.Numerics;
using Content.Client.RichText;
using Content.Client._VanGuard.Language; // VG-Tweak: language system
using Content.Shared._VanGuard.Language; // VG-Tweak: language system
using Content.Shared.Paper;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.Input;
using Robust.Client.Player; // VG-Tweak: language system
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;
using Robust.Client.UserInterface.RichText;
using Content.Client.UserInterface.RichText;
using Robust.Shared.Input;
using Robust.Shared.Prototypes; // VG-Tweak: language system

namespace Content.Client.Paper.UI
{
    [GenerateTypedNameReferences]
    public sealed partial class PaperWindow : BaseWindow
    {
        [Dependency] private IInputManager _inputManager = default!;
        [Dependency] private IResourceCache _resCache = default!;
        [Dependency] private IEntityManager _entityManager = default!; // VG-Tweak: language system
        [Dependency] private IPlayerManager _playerManager = default!; // VG-Tweak: language system
        [Dependency] private IPrototypeManager _prototypeManager = default!; // VG-Tweak: language system

        private static Color DefaultTextColor = new(25, 25, 25);

        // Default color for text which hasn't been changed using markup
        private Color _writtenTextColor = DefaultTextColor;

        // Size of resize handles around the paper
        private const int DRAG_MARGIN_SIZE = 16;

        // We keep a reference to the paper content texture that we create
        // so that we can modify it later.
        private StyleBoxTexture _paperContentTex = new();

        // The number of lines that the content image represents.
        // See PaperVisualsComponent.ContentImageNumLines.
        private float _paperContentLineScale = 1.0f;

        // If paper limits the size in one or both axes, it'll affect whether
        // we're able to resize this UI or not. Default to everything enabled:
        private DragMode _allowedResizeModes = ~DragMode.None;

        public event Action<string, List<PaperComponent.PaperTextSegment>>? OnSaved;

        // VG-Tweak Start: language system - language-tagged writing
        private readonly Dictionary<int, string> _languageIds = new();
        private readonly List<LanguageMarker> _languageMarkers = new();
        private string _selectedLanguage = SharedLanguageSystem.CommonLanguageId;
        private string _initialLanguage = SharedLanguageSystem.CommonLanguageId;
        private string _lastInputText = "";
        private bool _suppressLanguageTracking;
        private bool _languageSelectionChanged;
        private bool _updatingLanguageSelector;
        private List<PaperComponent.PaperTextSegment> _originalLanguageSegments = new();
        private List<PaperComponent.PaperTextSegment> _originalDisplaySegments = new();
        private string _originalEditableText = "";
        // VG-Tweak End

        private int _MaxInputLength = -1;
        public int MaxInputLength
        {
            get
            {
                return _MaxInputLength;
            }
            set
            {
                _MaxInputLength = value;
                UpdateFillState();
            }
        }

        public PaperWindow()
        {
            IoCManager.InjectDependencies(this);
            RobustXamlLoader.Load(this);

            // We can't configure the RichTextLabel contents from xaml, so do it here:
            BlankPaperIndicator.SetMessage(Loc.GetString("paper-ui-blank-page-message"), null, DefaultTextColor);
            LanguageLabel.Text = Loc.GetString("paper-ui-language-label");
            LanguageSelector.OnItemSelected += OnLanguageSelected;

            // Hook up the close button:
            CloseButton.OnPressed += _ => Close();

            Input.OnKeyBindDown += args => // Solution while TextEdit don't have events
            {
                if (args.Function == EngineKeyFunctions.MultilineTextSubmit)
                {
                    // SaveButton is disabled when we hit the max input limit. Just check
                    // that flag instead of trying to calculate the input length again
                    if (!SaveButton.Disabled)
                    {
                        RunOnSaved();
                        args.Handle();
                    }
                }
            };

            Input.OnTextChanged += args =>
            {
                UpdateFillState();
                UpdateLanguageMarkers();
            };

            SaveButton.OnPressed += _ =>
            {
                RunOnSaved();
            };

            SaveButton.Text = Loc.GetString("paper-ui-save-button",
                ("keybind", _inputManager.GetKeyFunctionButtonString(EngineKeyFunctions.MultilineTextSubmit)));
        }

        /// <summary>
        ///     Initialize this UI according to <code>visuals</code> Initializes
        ///     textures, recalculates sizes, and applies some layout rules.
        /// </summary>
        public void InitVisuals(EntityUid entity, PaperVisualsComponent visuals)
        {
            // Randomize the placement of any stamps based on the entity UID
            // so that there's some variety in different papers.
            StampDisplay.PlacementSeed = (int)entity;

            // Initialize the background:
            PaperBackground.ModulateSelfOverride = visuals.BackgroundModulate;
            var backgroundImage = visuals.BackgroundImagePath != null? _resCache.GetResource<TextureResource>(visuals.BackgroundImagePath) : null;
            if (backgroundImage != null)
            {
                var backgroundImageMode = visuals.BackgroundImageTile ? StyleBoxTexture.StretchMode.Tile : StyleBoxTexture.StretchMode.Stretch;
                var backgroundPatchMargin = visuals.BackgroundPatchMargin;
                PaperBackground.PanelOverride = new StyleBoxTexture
                {
                    Texture = backgroundImage,
                    TextureScale = visuals.BackgroundScale,
                    Mode = backgroundImageMode,
                    PatchMarginLeft = backgroundPatchMargin.Left,
                    PatchMarginBottom = backgroundPatchMargin.Bottom,
                    PatchMarginRight = backgroundPatchMargin.Right,
                    PatchMarginTop = backgroundPatchMargin.Top
                };

            }
            else
            {
                PaperBackground.PanelOverride = null;
            }


            // Then the header:
            if (visuals.HeaderImagePath != null)
            {
                HeaderImage.TexturePath = visuals.HeaderImagePath;
                HeaderImage.MinSize = HeaderImage.TextureNormal?.Size ?? Vector2.Zero;
            }

            HeaderImage.ModulateSelfOverride = visuals.HeaderImageModulate;
            HeaderImage.Margin = new Thickness(visuals.HeaderMargin.Left, visuals.HeaderMargin.Top,
                    visuals.HeaderMargin.Right, visuals.HeaderMargin.Bottom);

            // Then the footer
            if (visuals.FooterImagePath is {} path)
            {
                FooterImage.TexturePath = path.ToString();
                FooterImage.MinSize = FooterImage.TextureNormal?.Size ?? Vector2.Zero;
            }

            FooterImage.ModulateSelfOverride = visuals.FooterImageModulate;
            FooterImage.Margin = new Thickness(visuals.FooterMargin.Left, visuals.FooterMargin.Top,
                    visuals.FooterMargin.Right, visuals.FooterMargin.Bottom);

            PaperContent.ModulateSelfOverride = visuals.ContentImageModulate;
            _writtenTextColor = visuals.DefaultTextColor ?? DefaultTextColor;

            var contentImage = visuals.ContentImagePath != null ? _resCache.GetResource<TextureResource>(visuals.ContentImagePath) : null;
            if (contentImage != null)
            {
                // Setup the paper content texture, but keep a reference to it, as we can't set
                // some font-related properties here. We'll fix those up later, in Draw()
                _paperContentTex = new StyleBoxTexture
                {
                    Texture = contentImage,
                    Mode = StyleBoxTexture.StretchMode.Tile,
                };
                PaperContent.PanelOverride = _paperContentTex;
                _paperContentLineScale = visuals.ContentImageNumLines;
            }

            PaperContent.Margin = new Thickness(
                    visuals.ContentMargin.Left, visuals.ContentMargin.Top,
                    visuals.ContentMargin.Right, visuals.ContentMargin.Bottom);

            if (visuals.MaxWritableArea != null)
            {
                var a = (Vector2)visuals.MaxWritableArea;
                // Paper has requested that this has a maximum area that you can write on.
                // So, we'll make the window non-resizable and fix the size of the content.
                // Ideally, would like to be able to allow resizing only one direction.
                ScrollingContents.MinSize = Vector2.Zero;
                ScrollingContents.MinSize = a;

                if (a.X > 0.0f)
                {
                    ScrollingContents.MaxWidth = a.X;
                    _allowedResizeModes &= ~(DragMode.Left | DragMode.Right);

                    // Since this dimension has been specified by the user, we
                    // need to undo the SetSize which was configured in the xaml.
                    // Controls use NaNs to indicate unset for this value.
                    // This is leaky - there should be a method for this
                    SetWidth = float.NaN;
                }

                if (a.Y > 0.0f)
                {
                    ScrollingContents.MaxHeight = a.Y;
                    _allowedResizeModes &= ~(DragMode.Top | DragMode.Bottom);
                    SetHeight = float.NaN;
                }
            }
        }

        /// <summary>
        ///     Control interface. We'll mostly rely on the children to do the drawing
        ///     but in order to get lines on paper to match up with the rich text labels,
        ///     we need to do a small calculation to sync them up.
        /// </summary>
        protected override void Draw(DrawingHandleScreen handle)
        {
            // Now do the deferred setup of the written area. At the point
            // that InitVisuals runs, the label hasn't had it's style initialized
            // so we need to get some info out now:
            if (WrittenTextLabel.TryGetStyleProperty<Font>("font", out var font))
            {
                float fontLineHeight = font.GetLineHeight(1.0f);
                // This positions the texture so the font baseline is on the bottom:
                _paperContentTex.ExpandMarginTop = font.GetDescent(UIScale);
                // And this scales the texture so that it's a single text line:
                var scaleY = (_paperContentLineScale * fontLineHeight) / _paperContentTex.Texture?.Height ?? fontLineHeight;
                _paperContentTex.TextureScale = new Vector2(1, scaleY);

                // Now, we might need to add some padding to the text to ensure
                // that, even if a header is specified, the text will line up with
                // where the content image expects the font to be rendered (i.e.,
                // adjusting the height of the header image shouldn't cause the
                // text to be offset from a line)
                {
                    var headerHeight = HeaderImage.Size.Y + HeaderImage.Margin.Top + HeaderImage.Margin.Bottom;
                    var headerInLines = headerHeight / (fontLineHeight * _paperContentLineScale);
                    var paddingRequiredInLines = (float)Math.Ceiling(headerInLines) - headerInLines;
                    var verticalMargin = fontLineHeight * paddingRequiredInLines * _paperContentLineScale;
                    TextAlignmentPadding.Margin = new Thickness(0.0f, verticalMargin, 0.0f, 0.0f);
                }
            }

            base.Draw(handle);
        }

        /// <summary>
        ///     Initialize the paper contents, i.e. the text typed by the
        ///     user and any stamps that have peen put on the page.
        /// </summary>
        public void Populate(PaperComponent.PaperBoundUserInterfaceState state)
        {
            bool isEditing = state.Mode == PaperComponent.PaperAction.Write;
            bool wasEditing = InputContainer.Visible;
            InputContainer.Visible = isEditing;
            EditButtons.Visible = isEditing;
            _languageSelectionChanged = false; // VG-Tweak: language system

            var msg = new FormattedMessage();
            if (isEditing)
            {
                msg.AddMarkupPermissive(state.Text);
            }
            else
            {
                // VG-Tweak: show words written in a language the reader understands
                // tinted with that language's dim color; unreadable text stays gray.
                foreach (var (text, color) in GetReadableSegmentsWithColors(state))
                {
                    msg.PushColor(color);
                    msg.AddMarkupPermissive(text);
                    msg.Pop();
                }
            }

            // For premade documents, we want to be able to edit them rather than
            // replace them.
            var shouldCopyText = 0 == Input.TextLength && 0 != state.Text.Length;
            if (!wasEditing || shouldCopyText)
            {
                // We can get repeated messages with state.Mode == Write if another
                // player opens the UI for reading. In this case, don't update the
                // text input, as this player is currently writing new text and we
                // don't want to lose any text they already input.
                var editableSegments = GetReadableLanguageSegments(state).ToList();
                var editableText = string.Concat(editableSegments.Select(segment => segment.Text));
                _originalLanguageSegments = state.LanguageSegments
                    .Select(segment => new PaperComponent.PaperTextSegment(segment.Text, segment.Language, segment.ObfuscatedText))
                    .ToList();
                _originalDisplaySegments = editableSegments
                    .Select(segment => new PaperComponent.PaperTextSegment(segment.Text, segment.Language))
                    .ToList();
                _originalEditableText = editableText;

                _suppressLanguageTracking = true;
                Input.TextRope = Rope.Leaf.Empty;
                Input.CursorPosition = new TextEdit.CursorPos();
                Input.InsertAtCursor(editableText);
                _suppressLanguageTracking = false;
                LoadLanguageSegments(editableSegments, editableText);
            }

            if (isEditing)
                UpdateLanguageSelector();

            if (!isEditing)
                _lastInputText = state.Text;

            for (var i = 0; i <= state.StampedBy.Count * 3 + 1; i++)
            {
                msg.AddMarkupPermissive("\r\n");
            }
            WrittenTextLabel.SetMessage(msg, UserFormattableTags.BaseAllowedTags, _writtenTextColor);

            WrittenTextLabel.Visible = !isEditing && state.Text.Length > 0;
            BlankPaperIndicator.Visible = !isEditing && state.Text.Length == 0;

            StampDisplay.RemoveAllChildren();
            StampDisplay.RemoveStamps();
            foreach(var stamper in state.StampedBy)
            {
                StampDisplay.AddStamp(new StampWidget{ StampInfo = stamper });
            }
        }

        /// <summary>
        ///     BaseWindow interface. Allow users to drag UI around by grabbing
        ///     anywhere on the page (like FancyWindow) but try to calculate
        ///     reasonable dragging bounds because this UI can have round corners,
        ///     and it can be hard to judge where to click to resize.
        /// </summary>
        protected override DragMode GetDragModeFor(Vector2 relativeMousePos)
        {
            var mode = DragMode.None;

            // Be quite generous with resize margins:
            if (relativeMousePos.Y < DRAG_MARGIN_SIZE)
            {
                mode |= DragMode.Top;
            }
            else if (relativeMousePos.Y > Size.Y - DRAG_MARGIN_SIZE)
            {
                mode |= DragMode.Bottom;
            }

            if (relativeMousePos.X < DRAG_MARGIN_SIZE)
            {
                mode |= DragMode.Left;
            }
            else if (relativeMousePos.X > Size.X - DRAG_MARGIN_SIZE)
            {
                mode |= DragMode.Right;
            }

            if((mode & _allowedResizeModes) == DragMode.None)
            {
                return DragMode.Move;
            }
            return mode & _allowedResizeModes;
        }

        private void RunOnSaved()
        {
            // Prevent further saving while text processing still in
            SaveButton.Disabled = true;
            var editableText = Rope.Collapse(Input.TextRope);
            var segments = BuildLanguageSegments(editableText);

            // The text sent to the server must match the language segments exactly.
            // When the editor cannot read part of the original document, the input
            // field shows that part obfuscated, so the raw text has to be rebuilt
            // from the segments rather than taken verbatim from the input field.
            var text = string.Concat(segments.Select(segment => segment.Text));
            OnSaved?.Invoke(text, segments);
        }


        private void OnLanguageSelected(OptionButton.ItemSelectedEventArgs args)
        {
            if (_updatingLanguageSelector || !_languageIds.TryGetValue(args.Id, out var language))
                return;

            LanguageSelector.SelectId(args.Id);
            _selectedLanguage = language;
            _languageSelectionChanged = true;
            AddLanguageMarker(language);
        }

        private void UpdateLanguageSelector()
        {
            _updatingLanguageSelector = true;
            LanguageSelector.Clear();
            _languageIds.Clear();

            var languageSystem = _entityManager.System<LanguageSystem>();
            if (_playerManager.LocalEntity is { } player &&
                languageSystem.RetrieveKnownLanguages(player, LanguageKnowledge.BadSpeak, out var languages, out _))
            {
                foreach (var id in languages.Keys)
                    AddLanguageOption(id);
            }

            AddLanguageOption(SharedLanguageSystem.CommonLanguageId);

            if (_languageIds.Count > 0)
            {
                var selected = _languageIds.FirstOrDefault(pair => pair.Value == _selectedLanguage);
                if (selected.Value == _selectedLanguage)
                {
                    LanguageSelector.SelectId(selected.Key);
                }
                else
                {
                    // No matching language: select the deterministic first option
                    // (id 0) instead of relying on dictionary enumeration order, and
                    // keep the rest of the UI in sync with the dropdown.
                    LanguageSelector.SelectId(0);
                    _selectedLanguage = _languageIds[0];
                }
            }

            _updatingLanguageSelector = false;
        }

        private void AddLanguageOption(string id)
        {
            if (_languageIds.ContainsValue(id) || !_prototypeManager.TryIndex<LanguagePrototype>(id, out var prototype))
                return;

            // Gestural languages (sign language, diona leaves, slime bubbles) have
            // no written form and cannot be used when writing on paper.
            if (!prototype.Written)
                return;

            var optionId = _languageIds.Count;
            _languageIds.Add(optionId, id);
            LanguageSelector.AddItem(prototype.Name, optionId);
        }

        private void AddLanguageMarker(string language)
        {
            var position = Input.TextLength;
            if (position == 0)
            {
                _initialLanguage = language;
                return;
            }

            _languageMarkers.RemoveAll(marker => marker.Position == position);
            _languageMarkers.Add(new LanguageMarker(position, language));
            _languageMarkers.Sort((left, right) => left.Position.CompareTo(right.Position));
        }

        private void UpdateLanguageMarkers()
        {
            var text = Rope.Collapse(Input.TextRope);
            if (_suppressLanguageTracking)
            {
                _lastInputText = text;
                return;
            }

            if (text.Length < _lastInputText.Length)
            {
                _languageMarkers.RemoveAll(marker => marker.Position >= text.Length);
                // When the whole document is erased, retyped text follows the
                // language currently selected in the dropdown.
                if (text.Length == 0)
                    _initialLanguage = _selectedLanguage;
            }
            else if (!text.StartsWith(_lastInputText, StringComparison.Ordinal))
            {
                _languageMarkers.Clear();
                _initialLanguage = _selectedLanguage;
            }

            _lastInputText = text;
        }

        private void LoadLanguageSegments(List<PaperComponent.PaperTextSegment> segments, string text)
        {
            _languageMarkers.Clear();
            _initialLanguage = segments.Count > 0 ? segments[0].Language : SharedLanguageSystem.CommonLanguageId;
            _selectedLanguage = _initialLanguage;

            var offset = 0;
            for (var index = 0; index < segments.Count; index++)
            {
                var segment = segments[index];
                if (string.IsNullOrEmpty(segment.Text))
                    continue;

                offset += segment.Text.Length;
                _selectedLanguage = segment.Language;
                if (offset < text.Length)
                {
                    var nextLanguage = index + 1 < segments.Count ? segments[index + 1].Language : segment.Language;
                    _languageMarkers.Add(new LanguageMarker(offset, nextLanguage));
                }
            }

            // VG-Tweak Start: do not default newly typed text to a language the writer
            // cannot speak (for example, the last segment belongs to another author).
            // Fall back to the common tongue, which every sapient knows.
            if (_playerManager.LocalEntity is { } uid
                && _entityManager.System<LanguageSystem>() is { } languageSystem
                && !languageSystem.CanSpeak(uid, _selectedLanguage))
            {
                _selectedLanguage = SharedLanguageSystem.CommonLanguageId;
            }
            // VG-Tweak End

            _lastInputText = text;
        }


        private List<PaperComponent.PaperTextSegment> BuildLanguageSegments(string text)
        {
            if (text.Length == 0)
                return new List<PaperComponent.PaperTextSegment>();

            // The writer switched language and re-typed the same text (for example,
            // erased a word and typed it back in another language). The raw text did
            // not change, so the language markers recorded while editing are the only
            // hint about the new languages. This must be evaluated before the
            // unchanged-document branch so an explicit re-tag is not discarded.
            if (text == _originalEditableText && _originalLanguageSegments.Count > 0 && _languageSelectionChanged)
                return BuildSegmentsFromMarkers(text);

            // The document was not modified at all - keep the exact original segments.
            if (text == _originalEditableText && _originalLanguageSegments.Count > 0)
            {
                return _originalLanguageSegments
                    .Select(segment => new PaperComponent.PaperTextSegment(segment.Text, segment.Language, segment.ObfuscatedText))
                    .ToList();
            }

            // A brand new paper written in this session: the language markers recorded
            // while typing describe the language switches.
            if (_originalLanguageSegments.Count == 0)
                return BuildSegmentsFromMarkers(text);

            // Diff the new text against the original on a word-by-word basis. Words
            // the writer did not touch keep the language of the segment they came
            // from; every added or replaced word is written in the language currently
            // selected in the dropdown. This single rule covers appending, inserting,
            // replacing, deleting and mixing words in any order.
            var originalWords = SplitWordsWithLanguages(_originalEditableText, _originalDisplaySegments);
            var newWords = SplitWords(text);
            var matches = LongestCommonSubsequence(originalWords, newWords);

            var result = new List<PaperComponent.PaperTextSegment>();
            for (var index = 0; index < newWords.Count; index++)
            {
                if (matches[index] is { } originalIndex)
                {
                    var originalWord = originalWords[originalIndex];
                    AddLanguageSegment(result, GetRawWord(originalWord, newWords[index]), originalWord.Language);
                }
                else
                {
                    AddLanguageSegment(result, newWords[index], _selectedLanguage);
                }
            }

            return result;
        }

        /// <summary>
        ///     A single word of the original document and where it came from, so the
        ///     raw text of an obscured segment can be recovered when it is matched.
        /// </summary>
        private readonly record struct OriginalWord(string Text, string Language, int SegmentIndex, int WordIndex);

        /// <summary>
        ///     Splits text into words. Each word keeps its leading whitespace so the
        ///     concatenation of all words equals the original text.
        /// </summary>
        private static List<string> SplitWords(string text)
        {
            var words = new List<string>();
            if (text.Length == 0)
                return words;

            var start = 0;
            for (var index = 1; index <= text.Length; index++)
            {
                if (index < text.Length
                    && !char.IsWhiteSpace(text[index - 1])
                    && char.IsWhiteSpace(text[index]))
                {
                    words.Add(text[start..index]);
                    start = index;
                }
            }

            words.Add(text[start..]);
            return words;
        }

        /// <summary>
        ///     Splits the original document into words, tagging each word with the
        ///     language of the display segment it belongs to.
        /// </summary>
        private static List<OriginalWord> SplitWordsWithLanguages(string text, List<PaperComponent.PaperTextSegment> displaySegments)
        {
            var words = new List<OriginalWord>();
            for (var segmentIndex = 0; segmentIndex < displaySegments.Count; segmentIndex++)
            {
                var segment = displaySegments[segmentIndex];
                var segmentWords = SplitWords(segment.Text);
                for (var wordIndex = 0; wordIndex < segmentWords.Count; wordIndex++)
                    words.Add(new OriginalWord(segmentWords[wordIndex], segment.Language, segmentIndex, wordIndex));
            }

            return words;
        }

        /// <summary>
        ///     Longest common subsequence between the original words and the new words.
        ///     Returns, for each new word, the index of the original word it is matched
        ///     with, or null when the word is new.
        /// </summary>
        private static int?[] LongestCommonSubsequence(List<OriginalWord> original, List<string> newer)
        {
            var n = original.Count;
            var m = newer.Count;
            var dp = new int[n + 1, m + 1];

            for (var i = n - 1; i >= 0; i--)
            {
                for (var j = m - 1; j >= 0; j--)
                {
                    // Compare by word content, ignoring leading whitespace, so a word
                    // shifted by an insertion still matches its original.
                    dp[i, j] = string.Equals(original[i].Text.TrimStart(), newer[j].TrimStart(), StringComparison.Ordinal)
                        ? dp[i + 1, j + 1] + 1
                        : System.Math.Max(dp[i + 1, j], dp[i, j + 1]);
                }
            }

            var matches = new int?[m];
            var x = 0;
            var y = 0;
            while (x < n && y < m)
            {
                if (string.Equals(original[x].Text.TrimStart(), newer[y].TrimStart(), StringComparison.Ordinal))
                {
                    matches[y] = x;
                    x++;
                    y++;
                }
                else if (dp[x + 1, y] >= dp[x, y + 1])
                {
                    x++;
                }
                else
                {
                    y++;
                }
            }

            return matches;
        }

        /// <summary>
        ///     Returns the raw text of a matched original word. When the segment is
        ///     obscured for the writer, the display word cannot be stored as-is, so
        ///     the raw word at the same position within the segment is used instead.
        /// </summary>
        private string GetRawWord(OriginalWord word, string newWordText)
        {
            if (word.SegmentIndex >= 0 && word.SegmentIndex < _originalLanguageSegments.Count)
            {
                var raw = _originalLanguageSegments[word.SegmentIndex];

                if (word.SegmentIndex < _originalDisplaySegments.Count)
                {
                    var display = _originalDisplaySegments[word.SegmentIndex];

                    // The writer sees the segment as it really is: no mapping needed.
                    if (raw.Text == display.Text)
                        return newWordText;

                    var rawWords = SplitWords(raw.Text);
                    var displayWords = SplitWords(display.Text);

                    // Only trust the word-to-word mapping when both versions contain
                    // the same number of words; otherwise the display word cannot be
                    // translated back to its raw form.
                    if (word.WordIndex >= 0 && word.WordIndex < rawWords.Count
                        && word.WordIndex < displayWords.Count)
                    {
                        // Keep the whitespace the writer sees in front of the word, but
                        // substitute the raw (non-obscured) word content.
                        var leadingLength = newWordText.Length - newWordText.TrimStart().Length;
                        return newWordText[..leadingLength] + rawWords[word.WordIndex].TrimStart();
                    }
                }

                // The segment could not be mapped word-by-word: fall back to the raw
                // word at the same position inside the original segment instead of
                // writing the (possibly obfuscated) display text into the document.
                var rawWordsFallback = SplitWords(raw.Text);
                if (word.WordIndex >= 0 && word.WordIndex < rawWordsFallback.Count)
                {
                    var leadingLength = newWordText.Length - newWordText.TrimStart().Length;
                    return newWordText[..leadingLength] + rawWordsFallback[word.WordIndex].TrimStart();
                }
            }

            return newWordText;
        }

        /// <summary>
        ///     Rebuilds the language segments from the recorded language markers and
        ///     the initial language. Used when the writer explicitly re-tags text.
        /// </summary>
        private List<PaperComponent.PaperTextSegment> BuildSegmentsFromMarkers(string text)
        {
            var result = new List<PaperComponent.PaperTextSegment>();
            if (text.Length == 0)
                return result;

            var language = _initialLanguage;
            var start = 0;
            foreach (var marker in _languageMarkers.Where(marker => marker.Position > 0 && marker.Position < text.Length).OrderBy(marker => marker.Position))
            {
                if (marker.Position > start)
                    result.Add(new PaperComponent.PaperTextSegment(text[start..marker.Position], language));

                language = marker.Language;
                start = marker.Position;
            }

            if (start < text.Length)
                result.Add(new PaperComponent.PaperTextSegment(text[start..], language));

            return result;
        }

        private static void AddLanguageSegment(
            List<PaperComponent.PaperTextSegment> segments,
            string text,
            string language)
        {
            if (string.IsNullOrEmpty(text))
                return;

            if (segments.Count > 0 && segments[^1].Language == language)
            {
                segments[^1].Text += text;
                return;
            }

            segments.Add(new PaperComponent.PaperTextSegment(text, language));
        }

        private IEnumerable<PaperComponent.PaperTextSegment> GetReadableLanguageSegments(PaperComponent.PaperBoundUserInterfaceState state)
        {
            var languageSystem = _entityManager.System<LanguageSystem>();
            var player = _playerManager.LocalEntity;
            var segments = state.LanguageSegments.Count == 0
                ? new List<PaperComponent.PaperTextSegment> { new(state.Text, SharedLanguageSystem.CommonLanguageId) }
                : state.LanguageSegments;

            foreach (var segment in segments)
            {
                var understood = player is { } uid && languageSystem.CanUnderstand(uid, segment.Language);
                var text = understood
                    ? segment.Text
                    : string.IsNullOrEmpty(segment.ObfuscatedText)
                        ? ObfuscateUnknown(segment.Text)
                        : segment.ObfuscatedText;

                yield return new PaperComponent.PaperTextSegment(text, segment.Language);
            }
        }

        private IEnumerable<(string Text, Color Color)> GetReadableSegmentsWithColors(PaperComponent.PaperBoundUserInterfaceState state)
        {
            var languageSystem = _entityManager.System<LanguageSystem>();
            var player = _playerManager.LocalEntity;
            foreach (var segment in GetReadableLanguageSegments(state))
            {
                var understood = player is { } uid && languageSystem.CanUnderstand(uid, segment.Language);
                yield return (segment.Text, GetSegmentDisplayColor(segment.Language, understood));
            }
        }

        private Color GetSegmentDisplayColor(string language, bool understood)
        {
            if (understood && _prototypeManager.TryIndex<LanguagePrototype>(language, out var proto) && proto.UiColor is { } color)
            {
                // Dim the language's color so the words read as written in that language.
                return new Color(color.R * 0.65f, color.G * 0.65f, color.B * 0.65f, color.A);
            }

            // The common tongue (or a language without a color) keeps the default
            // writing color; text the reader cannot understand stays gray.
            return understood ? _writtenTextColor : new Color(0.45f, 0.45f, 0.45f, 1f);
        }

        private static string ObfuscateUnknown(string text)
        {
            return string.Concat(text.Select(character => character switch
            {
                '\n' or '\r' or '\t' => character,
                _ when char.IsWhiteSpace(character) => character,
                _ when char.IsPunctuation(character) => character,
                _ => '…'
            }));
        }

        private readonly record struct LanguageMarker(int Position, string Language);

        private void UpdateFillState()
        {
            if (MaxInputLength != -1)
            {
                var inputLength = Input.TextLength;

                FillStatus.Text = Loc.GetString("paper-ui-fill-level",
                    ("currentLength", inputLength),
                    ("maxLength", MaxInputLength));

                // Disable the save button if we've gone over the limit
                SaveButton.Disabled = inputLength > MaxInputLength;
            }
            else
            {
                FillStatus.Text = "";
                SaveButton.Disabled = false;
            }
        }
    }
}
