using System.Collections.Generic;
using System.Linq;
using System.Numerics;
using Content.Client.Lobby.UI.ProfileEditorControls;
using Content.Client.UserInterface.Controls;
using Content.Shared.Humanoid;
using Content.Shared.Preferences;
using Content.Shared.Roles;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Enums;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client.Lobby.UI;

[GenerateTypedNameReferences]
public sealed partial class LobbyCharacterPreviewPanel : Control
{
    // VG-Tweak Start
    [Dependency] private IClientPreferencesManager _preferencesManager = default!;
    [Dependency] private IPrototypeManager _prototypeManager = default!;
    [Dependency] private IResourceCache _resourceCache = default!;

    private LobbyUIController _controller;

    private List<KeyValuePair<int, HumanoidCharacterProfile>> _sortedCharacters = new();
    private int _leftSlot = -1;
    private int _rightSlot = -1;

    private static readonly Color _hiddenButtonColor = Color.Transparent;
    private static readonly Color _hoverButtonColor = Color.White.WithAlpha(0.15f);

    private RSI? _plusRsi;

    private ProfilePreviewSpriteView? _leftPreview;
    private ProfilePreviewSpriteView? _rightPreview;
    private Label? _leftLabel;
    private Label? _rightLabel;

    private bool _leftIsPlus = false;
    private bool _rightIsPlus = false;

    private Action<BaseButton.ButtonEventArgs>? _leftButtonHandler;
    private Action<BaseButton.ButtonEventArgs>? _rightButtonHandler;

    public LobbyCharacterPreviewPanel()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _controller = UserInterfaceManager.GetUIController<LobbyUIController>();

        SetupHoverEffects(LeftCharacterButton, isLeft: true);
        SetupHoverEffects(RightCharacterButton, isLeft: false);

        if (_resourceCache.TryGetResource<RSIResource>("/Textures/_VanGuard/Interface/Lobby/lobby_selector.rsi", out var rsiRes))
            _plusRsi = rsiRes.RSI;
    }

    private void SetupHoverEffects(Button button, bool isLeft)
    {
        button.OnMouseEntered += args =>
        {
            if (isLeft && _leftIsPlus)
                return;
            if (!isLeft && _rightIsPlus)
                return;

            button.ModulateSelfOverride = _hoverButtonColor;
        };

        button.OnMouseExited += args =>
        {
            if (isLeft && _leftIsPlus)
                return;
            if (!isLeft && _rightIsPlus)
                return;

            button.ModulateSelfOverride = _hiddenButtonColor;
        };
    }

    public void SetLoaded(bool value)
    {
        Loaded.Visible = value;
        Unloaded.Visible = !value;

        if (value)
        {
            UpdateCharacterSelector();
        }
    }

    public void SetSummaryText(string value)
    {
        var message = new FormattedMessage();
        message.AddText(value);
        Summary.SetMessage(message);
    }

    public void UpdateCharacterSelector()
    {
        if (!_preferencesManager.ServerDataLoaded || _preferencesManager.Preferences == null)
            return;

        var preferences = _preferencesManager.Preferences;
        _sortedCharacters = new List<KeyValuePair<int, HumanoidCharacterProfile>>(preferences.Characters);

        if (_sortedCharacters.Count == 0)
        {
            LeftCharacterButton.Visible = false;
            RightCharacterButton.Visible = false;
            return;
        }

        _sortedCharacters.Sort((a, b) => a.Key.CompareTo(b.Key));

        var selectedSlot = preferences.SelectedCharacterIndex;
        var selectedIndex = _sortedCharacters.FindIndex(c => c.Key == selectedSlot);
        if (selectedIndex < 0)
            selectedIndex = 0;

        int charCount = _sortedCharacters.Count;

        int leftIndex = -1;
        int rightIndex = -1;

        if (charCount == 1)
        {
            leftIndex = -1;
            rightIndex = -1;
        }
        else if (charCount == 2)
        {
            if (selectedIndex == 0)
            {
                leftIndex = -1;
                rightIndex = 1;
            }
            else
            {
                leftIndex = 0;
                rightIndex = -1;
            }
        }
        else
        {
            leftIndex = GetCycledIndex(selectedIndex, -1, charCount);
            rightIndex = GetCycledIndex(selectedIndex, 1, charCount);
        }

        var leftProfile = leftIndex >= 0 ? _sortedCharacters[leftIndex].Value : null;
        var rightProfile = rightIndex >= 0 ? _sortedCharacters[rightIndex].Value : null;

        int newLeftSlot = leftIndex >= 0 ? _sortedCharacters[leftIndex].Key : -1;
        int newRightSlot = rightIndex >= 0 ? _sortedCharacters[rightIndex].Key : -1;

        _leftSlot = newLeftSlot;
        _rightSlot = newRightSlot;

        LeftCharacterButton.Visible = false;
        RightCharacterButton.Visible = false;

        if (leftIndex == -1)
        {
            SetupPlusButton(LeftCharacterButton, isLeft: true);
            LeftCharacterButton.Visible = true;
            LeftCharacterButton.ModulateSelfOverride = _hiddenButtonColor;
        }
        else if (leftProfile != null)
        {
            SetupCharacterButton(LeftCharacterButton, leftProfile, newLeftSlot, isLeft: true);
            LeftCharacterButton.Visible = true;
            LeftCharacterButton.ModulateSelfOverride = _hiddenButtonColor;
        }

        if (rightIndex == -1)
        {
            SetupPlusButton(RightCharacterButton, isLeft: false);
            RightCharacterButton.Visible = true;
            RightCharacterButton.ModulateSelfOverride = _hiddenButtonColor;
        }
        else if (rightProfile != null)
        {
            SetupCharacterButton(RightCharacterButton, rightProfile, newRightSlot, isLeft: false);
            RightCharacterButton.Visible = true;
            RightCharacterButton.ModulateSelfOverride = _hiddenButtonColor;
        }
    }

    private void DetachLeftHandler()
    {
        if (_leftButtonHandler != null)
        {
            LeftCharacterButton.OnPressed -= _leftButtonHandler;
            _leftButtonHandler = null;
        }
    }

    private void DetachRightHandler()
    {
        if (_rightButtonHandler != null)
        {
            RightCharacterButton.OnPressed -= _rightButtonHandler;
            _rightButtonHandler = null;
        }
    }

    private void SetupPlusButton(Button button, bool isLeft)
    {
        if (isLeft)
            DetachLeftHandler();
        else
            DetachRightHandler();

        if (isLeft)
        {
            _leftPreview = null;
            _leftLabel = null;
        }
        else
        {
            _rightPreview = null;
            _rightLabel = null;
        }

        var textureButton = button.Children.FirstOrDefault() as TextureButton;
        if (textureButton == null)
        {
            button.DisposeAllChildren();

            textureButton = new TextureButton
            {
                SetSize = new Vector2(100, 100),
                HorizontalAlignment = HAlignment.Center,
                VerticalAlignment = VAlignment.Center
            };

            if (_plusRsi != null)
            {
                RSI.State? offState = null;
                RSI.State? onState = null;
                _plusRsi.TryGetState("dammy-off", out offState);
                _plusRsi.TryGetState("dammy-on", out onState);

                if (offState != null)
                    textureButton.TextureNormal = offState.Frame0;

                textureButton.OnMouseEntered += _ =>
                {
                    if (onState != null)
                        textureButton.TextureNormal = onState.Frame0;
                };
                textureButton.OnMouseExited += _ =>
                {
                    if (offState != null)
                        textureButton.TextureNormal = offState.Frame0;
                };
            }

            textureButton.OnPressed += _ =>
            {
                _controller.CreateCharacterAndOpenSetup();
            };

            button.AddChild(textureButton);
        }
        else
        {
            button.RemoveAllChildren();
            button.AddChild(textureButton);
        }

        if (isLeft)
            _leftIsPlus = true;
        else
            _rightIsPlus = true;
    }

    private void SetupCharacterButton(Button button, HumanoidCharacterProfile profile, int slot, bool isLeft)
    {
        if (isLeft)
            DetachLeftHandler();
        else
            DetachRightHandler();

        var preview = isLeft ? _leftPreview : _rightPreview;
        if (preview == null)
        {
            button.DisposeAllChildren();

            var box = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Vertical,
                HorizontalAlignment = HAlignment.Center,
                VerticalAlignment = VAlignment.Center,
                SeparationOverride = 2
            };

            preview = new ProfilePreviewSpriteView
            {
                Scale = new Vector2(3.75f, 3.75f),
                OverrideDirection = Direction.South,
                HorizontalAlignment = HAlignment.Center,
                SetSize = new Vector2(84, 84)
            };

            var label = new Label
            {
                HorizontalAlignment = HAlignment.Center,
                ClipText = true,
                MaxWidth = 80,
                Margin = new Thickness(0, 2)
            };

            box.AddChild(preview);
            box.AddChild(label);
            button.AddChild(box);

            if (isLeft)
            {
                _leftPreview = preview;
                _leftLabel = label;
            }
            else
            {
                _rightPreview = preview;
                _rightLabel = label;
            }
        }

        if (isLeft)
            _leftIsPlus = false;
        else
            _rightIsPlus = false;

        preview.LoadPreview(profile);
        var nameLabel = isLeft ? _leftLabel : _rightLabel;
        if (nameLabel != null)
            nameLabel.Text = profile.Name;

        var label3 = nameLabel;
        Action<BaseButton.ButtonEventArgs> handler = _ =>
        {
            if (slot >= 0)
                OnCharacterButtonPressed(slot);
        };

        if (isLeft)
            _leftButtonHandler = handler;
        else
            _rightButtonHandler = handler;

        button.OnPressed += handler;
    }

    private int GetCycledIndex(int currentIndex, int offset, int totalCount)
    {
        if (totalCount <= 1) return -1;
        int newIndex = currentIndex + offset;
        if (newIndex < 0) newIndex = totalCount - 1;
        else if (newIndex >= totalCount) newIndex = 0;
        return newIndex;
    }

    private void OnCharacterButtonPressed(int slot)
    {
        if (slot < 0) return;
        _controller.RequestCharacterSwitch(slot);
    }
    // VG-Tweak End
}