using Content.Client.Administration.Managers;
using Content.Client.Message;
using Content.Client.UserInterface.Systems.EscapeMenu;
using Content.Client._VanGuard.LobbyMessage;
using Robust.Client.AutoGenerated;
using Robust.Client.Console;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;

namespace Content.Client.Lobby.UI
{
    [GenerateTypedNameReferences]
    public sealed partial class LobbyGui : UIScreen
    {
        [Dependency] private IClientConsoleHost _consoleHost = default!;
        [Dependency] private IGameTiming _gameTiming = default!;
        [Dependency] private IClientAdminManager _adminManager = default!;

        private float _updateTimer;
        private LobbyGuiState _currentState = LobbyGuiState.Default;

        // Animation fields
        private bool _animating = false;
        private float _animStartTime;
        private float _animDuration = 0.3f;
        private Thickness _menuStartMargin, _chatStartMargin, _musicStartMargin;
        private Thickness _menuTargetMargin, _chatTargetMargin, _musicTargetMargin;
        private LobbyGuiState _targetState;

        public LobbyGui()
        {
            RobustXamlLoader.Load(this);
            IoCManager.InjectDependencies(this);

            SetAnchorPreset(MainContainer, LayoutPreset.Wide);
            SetAnchorPreset(Background, LayoutPreset.Wide);
            SetAnchorPreset(CharacterSetupState, LayoutPreset.Wide);

            LobbySong.SetMarkup(Loc.GetString("lobby-state-song-no-song-text"));
            LobbyBackground.SetMarkup(Loc.GetString("lobby-state-background-no-background-text"));

            LeaveButton.OnPressed += _ => _consoleHost.ExecuteCommand("disconnect");
            OptionsButton.OnPressed += _ => UserInterfaceManager.GetUIController<OptionsUIController>().ToggleWindow();

            HideInterface.OnPressed += _ =>
            {
                if (_currentState == LobbyGuiState.ScreenSaver)
                    SwitchState(LobbyGuiState.Default);
                else
                    SwitchState(LobbyGuiState.ScreenSaver);
            };

            CollapseButton.OnPressed += _ => TogglePanel(false);
            ExpandButton.OnPressed += _ => TogglePanel(true);

            CharacterSetup.OnPressed += _ =>
            {
                if (ReadyButton.Pressed)
                    _consoleHost.ExecuteCommand("toggleready False");

                UserInterfaceManager.GetUIController<LobbyUIController>().OpenCharacterSetup();
            };

            // VG-Tweak: Admin buttons
            StartRoundButton.OnPressed += _ => _consoleHost.ExecuteCommand("startround");
            DelayStartButton.OnPressed += _ => _consoleHost.ExecuteCommand("delaystart");
            SendLobbyMessageButton.OnPressed += _ => OpenVGMessageWindow();

            UpdateAdminButtons();
        }

        private void UpdateAdminButtons()
        {
            AdminButtons.Visible = _adminManager.IsActive();
        }

        // VG-Tweak: Добавление панели
        public void AddLobbyMessagePanel(VGMessagePanel panel)
        {
            VGMessageContainer.DisposeAllChildren();
            VGMessageContainer.AddChild(panel);
        }

        // VG-Tweak: Окно ввода сообщения для лобби
        private void OpenVGMessageWindow()
        {
            var window = new VGMessageWindow();
            window.OnSend += text =>
            {
                if (!string.IsNullOrWhiteSpace(text))
                {
                    if (text.Length > 100)
                        text = text[..100];
                    _consoleHost.ExecuteCommand($"vgsendmessage {text}");
                }
                else
                {
                    _consoleHost.ExecuteCommand("vgsendmessage");
                }
            };
            window.OpenCentered();
        }

        protected override void FrameUpdate(FrameEventArgs args)
        {
            base.FrameUpdate(args);

            if (!StartTime.Visible)
                StartTime.Visible = true;

            if (string.IsNullOrEmpty(StartTime.Text))
                StartTime.Text = "Раунд уже в процессе";

            _updateTimer += args.DeltaSeconds;
            if (_updateTimer > 5.0f)
            {
                _updateTimer = 0;
                UpdateAdminButtons();
            }

            if (_animating)
            {
                float elapsed = (float)(_gameTiming.CurTime.TotalSeconds - _animStartTime);
                float progress = Math.Clamp(elapsed / _animDuration, 0f, 1f);

                MenuControls.Margin = InterpolateMargin(_menuStartMargin, _menuTargetMargin, progress);
                ChatContainer.Margin = InterpolateMargin(_chatStartMargin, _chatTargetMargin, progress);
                MusicContainer.Margin = InterpolateMargin(_musicStartMargin, _musicTargetMargin, progress);

                if (progress >= 1f)
                {
                    _animating = false;
                    _currentState = _targetState;
                    ApplyFinalState();
                }
            }
        }

        private Thickness InterpolateMargin(Thickness a, Thickness b, float t)
        {
            return new Thickness(
                a.Left + (b.Left - a.Left) * t,
                a.Top + (b.Top - a.Top) * t,
                a.Right + (b.Right - a.Right) * t,
                a.Bottom + (b.Bottom - a.Bottom) * t);
        }

        public void SwitchState(LobbyGuiState state)
        {
            if (_currentState == state && !_animating)
                return;

            if (_animating)
            {
                MenuControls.Margin = _menuTargetMargin;
                ChatContainer.Margin = _chatTargetMargin;
                MusicContainer.Margin = _musicTargetMargin;
                _currentState = _targetState;
                ApplyFinalState();
                _animating = false;
            }

            if (state == LobbyGuiState.CharacterSetup)
            {
                _currentState = state;
                ApplyFinalState();
                return;
            }

            bool fromDefaultToSaver = (_currentState == LobbyGuiState.Default && state == LobbyGuiState.ScreenSaver);
            bool fromSaverToDefault = (_currentState == LobbyGuiState.ScreenSaver && state == LobbyGuiState.Default);

            if (fromDefaultToSaver || fromSaverToDefault)
            {
                _targetState = state;
                _animating = true;
                _animStartTime = (float)_gameTiming.CurTime.TotalSeconds;

                MenuControls.Visible = true;
                ChatContainer.Visible = true;
                MusicContainer.Visible = true;

                _menuStartMargin = MenuControls.Margin;
                _chatStartMargin = ChatContainer.Margin;
                _musicStartMargin = MusicContainer.Margin;

                if (state == LobbyGuiState.ScreenSaver)
                {
                    float menuWidth = MenuControls.Size.X;
                    float chatWidth = ChatContainer.Size.X;
                    float musicWidth = MusicContainer.Size.X;

                    _menuTargetMargin = new Thickness(-menuWidth, _menuStartMargin.Top, _menuStartMargin.Right, _menuStartMargin.Bottom);
                    _chatTargetMargin = new Thickness(_chatStartMargin.Left, _chatStartMargin.Top, -chatWidth, _chatStartMargin.Bottom);
                    _musicTargetMargin = new Thickness(-musicWidth, _musicStartMargin.Top, _musicStartMargin.Right, _musicStartMargin.Bottom);
                }
                else
                {
                    _menuTargetMargin = new Thickness(25, 25, 0, 45);
                    _chatTargetMargin = new Thickness(0, 100, 25, 25);
                    _musicTargetMargin = new Thickness(25, 0, 0, 15);
                }
            }
            else
            {
                _currentState = state;
                ApplyFinalState();
            }
        }

        private void ApplyFinalState()
        {
            DefaultState.Visible = false;
            CharacterSetupState.Visible = false;
            MainContainer.Visible = true;

            switch (_currentState)
            {
                case LobbyGuiState.Default:
                    DefaultState.Visible = true;
                    RightSide.Visible = true;
                    MenuControls.Margin = new Thickness(25, 25, 0, 45);
                    ChatContainer.Margin = new Thickness(0, 100, 25, 25);
                    MusicContainer.Margin = new Thickness(25, 0, 0, 15);
                    break;

                case LobbyGuiState.CharacterSetup:
                    CharacterSetupState.Visible = true;
                    MainContainer.Visible = false;
                    UserInterfaceManager.GetUIController<LobbyUIController>().ReloadCharacterSetup();
                    break;

                case LobbyGuiState.ScreenSaver:
                    MenuControls.Visible = false;
                    ChatContainer.Visible = false;
                    MusicContainer.Visible = false;
                    break;
            }
        }

        private void TogglePanel(bool value)
        {
            RightSide.Visible = value;
            ExpandPanel.Visible = !value;
        }

        public enum LobbyGuiState : byte
        {
            Default,
            CharacterSetup,
            ScreenSaver,
        }
    }
}