using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using System;
using System.Collections.Generic;

namespace Content.Client._VanGuard.Mining.OreBags.UI;

/// <summary>
/// Filter window for smart ore bags: checkboxes for every ore the bag can pick up.
/// Unchecked ores are added to the bag's ignore list.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class SmartOreBagWindow : FancyWindow
{
    [Dependency] private IPrototypeManager _proto = default!;

    /// <summary>
    /// All collectible ores (and artifact fragments) that smart ore bags can filter.
    /// </summary>
    private static readonly EntProtoId[] OreIds =
    [
        "SteelOre1",
        "SpaceQuartz1",
        "Coal1",
        "GoldOre1",
        "SilverOre1",
        "Salt1",
        "PlasmaOre1",
        "UraniumOre1",
        "BananiumOre1",
        "DiamondOre1",
        "ArtifactFragment1",
        "CopperOre1",
        "ZincOre1",
        "LeadOre1",
        "BluespaceOre1"
    ];

    private readonly List<EntProtoId> _initialIgnored = new();
    private readonly Dictionary<CheckBox, EntProtoId> _checkBoxMapping = new();

    /// <summary>
    /// Fired with the new ignore list when the player confirms the settings.
    /// </summary>
    public event Action<List<EntProtoId>>? OnConfirmed;

    public SmartOreBagWindow()
    {
        RobustXamlLoader.Load(this);

        SaveButton.OnPressed += OnSavePressed;
        SelectAllButton.OnPressed += OnSelectAllPressed;
    }

    public void UpdateState(List<EntProtoId> ignoredOres)
    {
        _initialIgnored.Clear();
        _initialIgnored.AddRange(ignoredOres);
        _checkBoxMapping.Clear();
        OreListContainer.RemoveAllChildren();

        BuildOreList();
        UpdateCount();
    }

    private void BuildOreList()
    {
        foreach (var oreId in OreIds)
        {
            var name = _proto.Index(oreId).Name;
            if (string.IsNullOrEmpty(name))
                name = oreId;

            var checkBox = new CheckBox
            {
                Text = name,
                Pressed = !_initialIgnored.Contains(oreId),
                Margin = new Thickness(6, 2),
            };

            _checkBoxMapping[checkBox] = oreId;
            OreListContainer.AddChild(checkBox);
        }
    }

    private void UpdateCount()
    {
        var total = _checkBoxMapping.Count;
        var pressed = 0;
        foreach (var checkBox in _checkBoxMapping.Keys)
        {
            if (checkBox.Pressed)
                pressed++;
        }

        CountLabel.Text = Loc.GetString("smart-ore-bag-ore-count", ("count", pressed), ("total", total));
    }

    private void OnSelectAllPressed(BaseButton.ButtonEventArgs args)
    {
        foreach (var checkBox in _checkBoxMapping.Keys)
            checkBox.Pressed = true;

        UpdateCount();
    }

    private void OnSavePressed(BaseButton.ButtonEventArgs args)
    {
        var ignored = new List<EntProtoId>();
        foreach (var (checkBox, protoId) in _checkBoxMapping)
        {
            if (!checkBox.Pressed)
                ignored.Add(protoId);
        }

        OnConfirmed?.Invoke(ignored);
        Close();
    }
}
